/**
 * CANADIAN ARMED FORCES (CAF) BASES, STATIONS & OVERSEAS OPERATIONAL HUBS
 * Comprehensive official geospatial dataset of Department of National Defence (DND) installations.
 * Includes Royal Canadian Air Force (RCAF) Wings, Royal Canadian Navy (RCN) Fleet Bases,
 * Canadian Army Divisional Bases, Northern Forward Operating Locations (FOLs), 
 * and International Operational Support Hubs (OSH) & NATO Deployments.
 */

export const CANADIAN_FORCES_BASES = [
  // =========================================================================
  // 1. ROYAL CANADIAN NAVY (RCN) FLEET BASES & ARCTIC FACILITIES
  // =========================================================================
  {
    id: 'cfb-halifax',
    name: 'CFB Halifax',
    wing: 'MARLANT HQ',
    designation: 'Atlantic Fleet Headquarters & HMC Dockyard',
    branch: 'rcn',
    branchLabel: 'Royal Canadian Navy',
    type: 'Naval Base & Fleet Dockyard',
    lat: 44.6560,
    lng: -63.5930,
    province: 'Nova Scotia',
    country: 'Canada',
    units: 'CANFLTLANT, HMC Dockyard, Stadacona, CFAD Bedford, Halifax-class Frigates, Kingston-class MCDVs',
    details: 'Canada\'s primary East Coast naval base and headquarters of Maritime Forces Atlantic (MARLANT). Hosts Canada\'s Atlantic surface and sub-surface fleet.',
    badge: '⚓'
  },
  {
    id: 'cfb-esquimalt',
    name: 'CFB Esquimalt',
    wing: 'MARPAC HQ',
    designation: 'Pacific Fleet Headquarters & HMC Dockyard',
    branch: 'rcn',
    branchLabel: 'Royal Canadian Navy',
    type: 'Naval Base & Fleet Dockyard',
    lat: 48.4320,
    lng: -123.4300,
    province: 'British Columbia',
    country: 'Canada',
    units: 'CANFLTPAC, HMC Dockyard Esquimalt, Naden, Albert Head, Victoria-class Submarines, Harry DeWolf-class AOPVs',
    details: 'Headquarters of Maritime Forces Pacific (MARPAC) and Joint Task Force Pacific (JTFP). Canada\'s primary naval base on the Pacific Rim.',
    badge: '⚓'
  },
  {
    id: 'nanisivik-naval-facility',
    name: 'Nanisivik Naval Facility',
    wing: 'Arctic Naval Deep-Water Berthing',
    designation: 'Arctic Deep-Water Naval Station',
    branch: 'rcn',
    branchLabel: 'Royal Canadian Navy',
    type: 'Arctic Naval Refueling Station',
    lat: 73.0683,
    lng: -84.5489,
    province: 'Nunavut',
    country: 'Canada',
    units: 'Operation NANOOK, Harry DeWolf-class Arctic Offshore Patrol Vessels (AOPV)',
    details: 'High Arctic deep-water naval facility in Strathcona Sound on Baffin Island, providing dedicated naval berthing and fuel bunkering for northern patrols.',
    badge: '⚓'
  },

  // =========================================================================
  // 2. ROYAL CANADIAN AIR FORCE (RCAF) WINGS & AIR BASES
  // =========================================================================
  {
    id: 'cfb-bagotville',
    name: 'CFB Bagotville',
    wing: '3 Wing Bagotville',
    designation: 'Eastern Interceptor Fighter Base',
    branch: 'rcaf',
    branchLabel: 'Royal Canadian Air Force',
    type: 'Fighter Wing & NORAD QRA Hub',
    lat: 48.3308,
    lng: -70.9964,
    province: 'Quebec',
    country: 'Canada',
    units: '425 Tactical Fighter Sqn (CF-188 Hornet), 433 Tactical Fighter Sqn, 439 Combat Support Sqn, 12 Radar Sqn',
    details: 'Primary fighter base safeguarding eastern Canadian and North American airspace under NORAD Quick Reaction Alert (QRA). Slated for next-gen F-35A fighters.',
    badge: '✈'
  },
  {
    id: 'cfb-cold-lake',
    name: 'CFB Cold Lake',
    wing: '4 Wing Cold Lake',
    designation: 'Western Interceptor Fighter Base',
    branch: 'rcaf',
    branchLabel: 'Royal Canadian Air Force',
    type: 'Fighter Wing & Weapons Testing',
    lat: 54.4050,
    lng: -110.2794,
    province: 'Alberta',
    country: 'Canada',
    units: '409 Tactical Fighter Sqn, 410 Tactical Fighter (Operational Training) Sqn, 417 Combat Support Sqn, AETE',
    details: 'Busiest fighter base in Canada. Controls the vast Primrose Lake Air Weapons Range (CLAWR) and hosts exercise Maple Flag.',
    badge: '✈'
  },
  {
    id: 'cfb-goose-bay',
    name: 'CFB Goose Bay',
    wing: '5 Wing Goose Bay',
    designation: 'Transatlantic & Arctic Gateway Base',
    branch: 'rcaf',
    branchLabel: 'Royal Canadian Air Force',
    type: 'Strategic Air Base & Low-Level Training',
    lat: 53.3192,
    lng: -60.4258,
    province: 'Newfoundland and Labrador',
    country: 'Canada',
    units: '444 Combat Support Sqn (CH-146 Griffon), NORAD Forward Operating Location, NATO low-level flight corridors',
    details: 'Crucial strategic staging base for North American defence, transatlantic air bridges, and Arctic sovereignty operations in Labrador.',
    badge: '✈'
  },
  {
    id: 'cfb-trenton',
    name: 'CFB Trenton',
    wing: '8 Wing Trenton',
    designation: 'Strategic Air Mobility & National SAR Hub',
    branch: 'rcaf',
    branchLabel: 'Royal Canadian Air Force',
    type: 'National Air Transport Center',
    lat: 44.1189,
    lng: -77.5281,
    province: 'Ontario',
    country: 'Canada',
    units: '424 Transport & Rescue Sqn, 429 Transport Sqn (CC-177 Globemaster III), 436 Transport Sqn (CC-130J), 437 Transport Sqn (Polaris/Husky), DART',
    details: 'Heart of RCAF air mobility and national disaster response (DART). Conducts worldwide strategic and tactical airlift and Central Canada SAR.',
    badge: '✈'
  },
  {
    id: 'cfb-gander',
    name: 'CFB Gander',
    wing: '9 Wing Gander',
    designation: 'Primary North Atlantic Search & Rescue Base',
    branch: 'rcaf',
    branchLabel: 'Royal Canadian Air Force',
    type: 'Search and Rescue Wing',
    lat: 48.9369,
    lng: -54.5681,
    province: 'Newfoundland and Labrador',
    country: 'Canada',
    units: '103 Search and Rescue Squadron (CH-149 Cormorant helicopters)',
    details: 'Responsible for SAR across maritime Eastern Canada, the Grand Banks, and the North Atlantic storm zones under Joint Rescue Coordination Centre (JRCC) Halifax.',
    badge: '✈'
  },
  {
    id: 'cfb-shearwater',
    name: 'CFB Shearwater',
    wing: '12 Wing Shearwater',
    designation: 'Maritime Helicopter Operations Base',
    branch: 'rcaf',
    branchLabel: 'Royal Canadian Air Force',
    type: 'Naval Aviation Wing',
    lat: 44.6397,
    lng: -63.4994,
    province: 'Nova Scotia',
    country: 'Canada',
    units: '406 Maritime Operational Training Sqn, 423 Maritime Helicopter Sqn (CH-148 Cyclone)',
    details: 'Center of RCAF naval aviation. Operates CH-148 Cyclone helicopters embarking aboard Royal Canadian Navy Halifax-class frigates and naval vessels.',
    badge: '✈'
  },
  {
    id: 'cfb-greenwood',
    name: 'CFB Greenwood',
    wing: '14 Wing Greenwood',
    designation: 'Long-Range ASW & Maritime Patrol Base',
    branch: 'rcaf',
    branchLabel: 'Royal Canadian Air Force',
    type: 'Maritime Patrol & Reconnaissance Wing',
    lat: 44.9844,
    lng: -64.9169,
    province: 'Nova Scotia',
    country: 'Canada',
    units: '404 Long Range Patrol and Training Sqn, 405 Long Range Patrol Sqn (CP-140 Aurora / P-8A Poseidon), 413 Transport and Rescue Sqn',
    details: 'Largest operational air base on the East Coast. Executes long-range anti-submarine warfare (ASW), maritime sovereignty patrol, and air SAR.',
    badge: '✈'
  },
  {
    id: 'cfb-moose-jaw',
    name: 'CFB Moose Jaw',
    wing: '15 Wing Moose Jaw',
    designation: 'National Flying Training Centre (NFTC)',
    branch: 'rcaf',
    branchLabel: 'Royal Canadian Air Force',
    type: 'Pilot Training & Aerobatic Flight Base',
    lat: 50.3303,
    lng: -105.5592,
    province: 'Saskatchewan',
    country: 'Canada',
    units: '2 Canadian Forces Flying Training School (CT-156 Harvard II, CT-155 Hawk), 431 Air Demonstration Sqn (The Snowbirds)',
    details: 'Principal pilot training academy for the RCAF and home of Canada\'s world-renowned Snowbirds aerobatic demonstration team.',
    badge: '✈'
  },
  {
    id: 'cfb-borden-16wing',
    name: 'CFB Borden (16 Wing)',
    wing: '16 Wing Borden',
    designation: 'Birthplace of the RCAF & Technical Academy',
    branch: 'rcaf',
    branchLabel: 'Royal Canadian Air Force',
    type: 'Air Technical Training Wing',
    lat: 44.2747,
    lng: -79.9142,
    province: 'Ontario',
    country: 'Canada',
    units: 'Canadian Forces School of Aerospace Technology and Engineering (CFSATE), Air Force Academy',
    details: 'Historic birthplace of military aviation in Canada (1917). Trains avionics, aviation technicians, and RCAF non-commissioned leaders.',
    badge: '✈'
  },
  {
    id: 'cfb-winnipeg',
    name: 'CFB Winnipeg',
    wing: '17 Wing Winnipeg',
    designation: '1 Canadian Air Division HQ & Canadian NORAD Region HQ',
    branch: 'rcaf',
    branchLabel: 'Royal Canadian Air Force',
    type: 'Operational Air Command & Air Combat Academy',
    lat: 49.9100,
    lng: -97.2397,
    province: 'Manitoba',
    country: 'Canada',
    units: '1 Canadian Air Division / CANR Headquarters, 402 City of Winnipeg Sqn (CT-142 Dash 8), 435 Transport and Rescue Sqn (Hercules)',
    details: 'Command nexus for all RCAF operational air squadrons and Canada\'s command node in the North American Aerospace Defense Command (NORAD).',
    badge: '✈'
  },
  {
    id: 'cfb-comox',
    name: 'CFB Comox',
    wing: '19 Wing Comox',
    designation: 'Pacific Maritime Patrol & SAR Base',
    branch: 'rcaf',
    branchLabel: 'Royal Canadian Air Force',
    type: 'Pacific Maritime Aviation Wing',
    lat: 49.7108,
    lng: -124.8867,
    province: 'British Columbia',
    country: 'Canada',
    units: '407 Long Range Patrol Sqn (CP-140 Aurora), 442 Transport and Rescue Sqn (CC-295 Kingfisher, CH-149 Cormorant), CFS METC',
    details: 'Monitors the Pacific approaches of Canada. Provides round-the-clock air search and rescue for Western Canada, Alaska border, and offshore Pacific waters.',
    badge: '✈'
  },
  {
    id: 'cfb-north-bay',
    name: 'CFB North Bay',
    wing: '22 Wing North Bay',
    designation: 'Canadian Air Defence Sector (CADS / NORAD)',
    branch: 'rcaf',
    branchLabel: 'Royal Canadian Air Force',
    type: 'Aerospace Control & Command Facility',
    lat: 46.3636,
    lng: -79.4228,
    province: 'Ontario',
    country: 'Canada',
    units: 'Canadian Air Defence Sector (CADS), 21 Aerospace Control and Warning Sqn, David L. Pitcher Complex',
    details: 'Responsible for round-the-clock air surveillance, identification, and interceptor control over all Canadian sovereign airspace in partnership with NORAD.',
    badge: '✈'
  },
  {
    id: '1-wing-kingston',
    name: '1 Wing Kingston',
    wing: '1 Wing Tactical Aviation HQ',
    designation: 'Tactical Aviation Operational Headquarters',
    branch: 'rcaf',
    branchLabel: 'Royal Canadian Air Force',
    type: 'Tactical Helicopter Wing HQ',
    lat: 44.2253,
    lng: -76.4950,
    province: 'Ontario',
    country: 'Canada',
    units: 'Headquarters for 6 tactical helicopter squadrons across Canada (CH-146 Griffon, CH-147F Chinook)',
    details: 'Commands all Army-support tactical aviation units and heavy lift helicopter forces across the Canadian Armed Forces.',
    badge: '✈'
  },

  // =========================================================================
  // 3. CANADIAN ARMY BASES & DIVISIONAL SUPPORT BASES (CDSB)
  // =========================================================================
  {
    id: 'cfb-edmonton',
    name: 'CFB Edmonton',
    wing: '3 CDSB Edmonton',
    designation: '3rd Canadian Division Headquarters & Steele Barracks',
    branch: 'army',
    branchLabel: 'Canadian Army',
    type: 'Armoured & Mechanized Brigade Base',
    lat: 53.6700,
    lng: -113.4700,
    province: 'Alberta',
    country: 'Canada',
    units: '3rd Canadian Division HQ, 1 Canadian Mechanized Brigade Group (1 CMBG), Lord Strathcona\'s Horse (Royal Canadians), 1 PPCLI, 3 PPCLI, 408 Tactical Helicopter Sqn',
    details: 'Major western army garrison housing heavy armour (Leopard 2 tanks), mechanized infantry battalions, and high-readiness brigades.',
    badge: '⚔'
  },
  {
    id: 'cfb-petawawa',
    name: 'CFB Petawawa',
    wing: '4 CDSB Petawawa',
    designation: '2 CMBG & Canadian Special Operations Regiment (CSOR)',
    branch: 'army',
    branchLabel: 'Canadian Army',
    type: 'Rapid Reaction Brigade & Special Forces Base',
    lat: 45.9000,
    lng: -77.2833,
    province: 'Ontario',
    country: 'Canada',
    units: '2 Canadian Mechanized Brigade Group (2 CMBG), The Royal Canadian Regiment (1 RCR, 3 RCR), Canadian Special Operations Regiment (CSOR), 427 Special Operations Aviation Sqn',
    details: 'Primary quick-deployment base for Eastern Canada. Houses Canada\'s elite Tier 1/2 special operations forces and rapid airborne assault units.',
    badge: '⚔'
  },
  {
    id: 'cfb-gagetown',
    name: 'CFB Gagetown',
    wing: '5 CDSB Gagetown',
    designation: 'Combat Training Centre (CTC) & 5th Division Base',
    branch: 'army',
    branchLabel: 'Canadian Army',
    type: 'Combat Training Center & Armoured Range',
    lat: 45.8333,
    lng: -66.4500,
    province: 'New Brunswick',
    country: 'Canada',
    units: 'Combat Training Centre (CTC), Tactics School, Infantry School, Armour School, Artillery School, 2 RCR, 403 Helicopter Operational Training Sqn',
    details: 'Second largest military base in Canada and primary ground combat training area with over 1,100 square kilometers of tactical live-fire ranges.',
    badge: '⚔'
  },
  {
    id: 'cfb-valcartier',
    name: 'CFB Valcartier',
    wing: '2 CDSB Valcartier',
    designation: '5 CMBG & Royal 22e Régiment ("Van Doos")',
    branch: 'army',
    branchLabel: 'Canadian Army',
    type: 'Francophone Mechanized Brigade Base',
    lat: 46.8833,
    lng: -71.4833,
    province: 'Quebec',
    country: 'Canada',
    units: '5 Canadian Mechanized Brigade Group (5 CMBG), 1R22eR, 2R22eR, 3R22eR, 12e Régiment blindé du Canada, 430 Tactical Helicopter Sqn, DRDC Valcartier',
    details: 'Home of the historic Royal 22e Régiment and major defence research laboratories (DRDC). Canada\'s primary French-speaking mechanized brigade.',
    badge: '⚔'
  },
  {
    id: 'cfb-kingston',
    name: 'CFB Kingston',
    wing: 'Vimy Barracks',
    designation: 'Joint Task Force HQ & Signals Communications Base',
    branch: 'army',
    branchLabel: 'Canadian Army',
    type: 'Joint Communications & Cyber Command Base',
    lat: 44.2333,
    lng: -76.4667,
    province: 'Ontario',
    country: 'Canada',
    units: 'Canadian Forces Joint Headquarters (CFJHQ), 1st Canadian Division HQ, Canadian Forces School of Communications and Electronics (CFSCE), Royal Military College (RMC)',
    details: 'Nexus for international joint task force command, military intelligence, electronic warfare, and officer academic commissioning (RMC).',
    badge: '⚔'
  },
  {
    id: 'cfb-shilo',
    name: 'CFB Shilo',
    wing: 'Home of the Royal Artillery',
    designation: 'Artillery & Mechanized Infantry Base',
    branch: 'army',
    branchLabel: 'Canadian Army',
    type: 'Artillery & Maneuver Training Base',
    lat: 49.8000,
    lng: -99.6333,
    province: 'Manitoba',
    country: 'Canada',
    units: '1st Regiment Royal Canadian Horse Artillery (1 RCHA), 2nd Battalion Princess Patricia\'s Canadian Light Infantry (2 PPCLI)',
    details: 'Primary artillery training center in Western Canada with extensive tactical artillery firing ranges.',
    badge: '⚔'
  },
  {
    id: 'cfb-suffield',
    name: 'CFB Suffield',
    wing: 'Largest Live-Fire Military Range',
    designation: 'Armoured Live-Fire & CBRN Defence Range',
    branch: 'army',
    branchLabel: 'Canadian Army',
    type: 'Heavy Armoured Live-Fire Training Area',
    lat: 50.2667,
    lng: -111.1833,
    province: 'Alberta',
    country: 'Canada',
    units: 'British Army Training Unit Suffield (BATUS) historically, DRDC Suffield (Defence R&D Chemical/Biological/Radiological Defence)',
    details: 'Spans 2,700 square kilometers—the largest military training area in Canada. Hosts heavy armored live-fire maneuver and CBRN defense research.',
    badge: '⚔'
  },
  {
    id: 'cfb-wainwright',
    name: 'CFB Wainwright',
    wing: 'Canadian Manoeuvre Training Centre',
    designation: 'National Force-on-Force Simulation Center',
    branch: 'army',
    branchLabel: 'Canadian Army',
    type: 'Manoeuvre & Tactical Training Base',
    lat: 52.8333,
    lng: -110.8667,
    province: 'Alberta',
    country: 'Canada',
    units: 'Canadian Manoeuvre Training Centre (CMTC), 3rd Canadian Division Training Centre, Exercise Maple Resolve',
    details: 'Hosts Exercise Maple Resolve, the Canadian Army\'s largest annual multinational validation exercise utilizing live combat simulation sensors.',
    badge: '⚔'
  },
  {
    id: 'cfb-borden-army',
    name: 'CFB Borden (Army/Tri-Service)',
    wing: 'Canadian Forces Support Training Group',
    designation: 'National Logistics, Health & Technical Academy',
    branch: 'army',
    branchLabel: 'Canadian Army',
    type: 'Tri-Service Training Base',
    lat: 44.2800,
    lng: -79.9000,
    province: 'Ontario',
    country: 'Canada',
    units: 'CFSATE, CFALST, Canadian Forces Health Services Training Centre, Canadian Forces Military Police Academy',
    details: 'Largest training base in the Canadian Armed Forces, educating thousands of regular and reserve force recruits, medics, engineers, and military police yearly.',
    badge: '⚔'
  },
  {
    id: 'cfb-montreal',
    name: 'CFB Montreal',
    wing: '2 CDSB Montreal',
    designation: 'Central Logistics & Materiel Supply Depot',
    branch: 'army',
    branchLabel: 'Canadian Army',
    type: 'Logistics Command & Equipment Depot',
    lat: 45.5861,
    lng: -73.5358,
    province: 'Quebec',
    country: 'Canada',
    units: '25 Canadian Forces Supply Depot (25 CFSD), 2nd Canadian Division Support Group, Saint-Hubert Detachment',
    details: 'Central logistical hub warehousing, servicing, and transporting combat vehicles, armaments, and supplies across Canada and overseas missions.',
    badge: '⚔'
  },
  {
    id: 'cfb-saint-jean',
    name: 'CFB Saint-Jean',
    wing: 'CFLRS Mega-Complex',
    designation: 'Canadian Forces Leadership and Recruit School',
    branch: 'joint',
    branchLabel: 'Tri-Service Joint Base',
    type: 'National Recruit Training Academy',
    lat: 45.3000,
    lng: -73.2833,
    province: 'Quebec',
    country: 'Canada',
    units: 'Canadian Forces Leadership and Recruit School (CFLRS), Royal Military College Saint-Jean',
    details: 'Gateway to the Canadian Armed Forces. Every newly enlisted non-commissioned member and officer candidate undertakes basic military qualification here.',
    badge: '🍁'
  },
  {
    id: '4-cdtc-meaford',
    name: '4 CDTC Meaford',
    wing: '4th Canadian Division Training Centre',
    designation: 'Ontario Maneuver & Live-Fire Training Center',
    branch: 'army',
    branchLabel: 'Canadian Army',
    type: 'Field Training Range',
    lat: 44.6000,
    lng: -80.6000,
    province: 'Ontario',
    country: 'Canada',
    units: '4th Canadian Division field qualification training battalions',
    details: 'Located on Georgian Bay, provides artillery, infantry, and armor live-fire ranges for primary combat units across Ontario.',
    badge: '⚔'
  },
  {
    id: 'cfad-dundurn',
    name: 'CFAD Dundurn',
    wing: 'Detachment Shilo',
    designation: 'Central Canadian Ammunition Depot & Range',
    branch: 'army',
    branchLabel: 'Canadian Army',
    type: 'Munitions Depot & Training Area',
    lat: 51.8167,
    lng: -106.5167,
    province: 'Saskatchewan',
    country: 'Canada',
    units: 'Canadian Forces Ammunition Depot (CFAD), Western tactical training area',
    details: 'Major national ordnance facility maintaining specialized munitions storage and field training areas south of Saskatoon.',
    badge: '⚔'
  },

  // =========================================================================
  // 4. STRATEGIC HEADQUARTERS, SIGNALS & JOINT STATIONS
  // =========================================================================
  {
    id: 'ndhq-carling',
    name: 'National Defence HQ (Carling Campus)',
    wing: 'Strategic Military Command',
    designation: 'Department of National Defence & CAF Headquarters',
    branch: 'joint',
    branchLabel: 'Strategic Joint Command',
    type: 'National Military Headquarters',
    lat: 45.3517,
    lng: -75.8567,
    province: 'Ontario',
    country: 'Canada',
    units: 'Chief of the Defence Staff, Strategic Joint Staff, Canadian Joint Operations Command (CJOC), Canadian Special Operations Forces Command (CANSOFCOM)',
    details: 'Canada\'s military nerve center and high command, directing all global and domestic Canadian Armed Forces operations.',
    badge: '🍁'
  },
  {
    id: 'cfs-leitrim',
    name: 'CFS Leitrim',
    wing: 'Information Operations Group',
    designation: 'Signals Intelligence & Cyber Operations Station',
    branch: 'joint',
    branchLabel: 'Signals Intelligence & Cyber Command',
    type: 'SIGINT & EW Intercept Station',
    lat: 45.3333,
    lng: -75.5833,
    province: 'Ontario',
    country: 'Canada',
    units: 'Canadian Forces Information Operations Group (CFIOG), Canadian Forces Network Operations Centre (CFNOC), Communications Security Establishment (CSE) liaison',
    details: 'Oldest continuously operating SIGINT station in Canada. Monitors military communications, electronic signals, and cyber warfare networks.',
    badge: '🍁'
  },
  {
    id: 'cfsu-stjohns',
    name: 'CFS / CFSU St. John\'s',
    wing: 'Pleasantville Naval Station',
    designation: 'Easternmost Canadian Military Station',
    branch: 'joint',
    branchLabel: 'Joint Eastern Command',
    type: 'Naval & Joint Support Unit',
    lat: 47.5833,
    lng: -52.7000,
    province: 'Newfoundland and Labrador',
    country: 'Canada',
    units: 'CFSU St. John\'s, HMCS Cabot, 37 Canadian Brigade Group detachments',
    details: 'Supports maritime operations, joint reserves, and air rescue units on the Avalon Peninsula of Newfoundland.',
    badge: '🍁'
  },

  // =========================================================================
  // 5. HIGH ARCTIC & NORTHERN BASES / FORWARD OPERATING LOCATIONS (FOL)
  // =========================================================================
  {
    id: 'cfs-alert',
    name: 'CFS Alert',
    wing: 'High Arctic Signals & Weather Station',
    designation: 'Northernmost Permanently Inhabited Base on Earth',
    branch: 'arctic',
    branchLabel: 'Arctic Sovereignty & Intelligence',
    type: 'High Arctic SIGINT & Research Base',
    lat: 82.4992,
    lng: -62.3481,
    province: 'Nunavut',
    country: 'Canada',
    units: 'Canadian Forces Information Operations Group (CFIOG), Environment Canada Weather Observatory, Operation BOXTOP',
    details: 'Situated only 817 kilometers from the North Pole on Ellesmere Island. Vital strategic sensor station monitoring Arctic airspace and satellite telemetry.',
    badge: '❄'
  },
  {
    id: 'jtfn-hq-yellowknife',
    name: 'Joint Task Force North (JTFN) HQ',
    wing: 'Northern Military Headquarters',
    designation: 'Arctic Territorial Command Headquarters',
    branch: 'arctic',
    branchLabel: 'Arctic Territorial Command',
    type: 'Northern Operations Command',
    lat: 62.4540,
    lng: -114.3718,
    province: 'Northwest Territories',
    country: 'Canada',
    units: 'Joint Task Force North HQ, 1st Canadian Ranger Patrol Group (1 CRPG), 440 Transport Sqn (CC-138 Twin Otter)',
    details: 'Command center for all Canadian military sovereignty missions across the Yukon, Northwest Territories, and Nunavut (approx 40% of Canada\'s landmass).',
    badge: '❄'
  },
  {
    id: 'fol-inuvik',
    name: 'FOL Inuvik (Mike Zubko Airport)',
    wing: 'Northern Operational Support Hub',
    designation: 'Western Arctic NORAD Forward Operating Location',
    branch: 'arctic',
    branchLabel: 'NORAD Arctic Forward Base',
    type: 'Fighter & Transport Staging Facility',
    lat: 68.3042,
    lng: -133.4828,
    province: 'Northwest Territories',
    country: 'Canada',
    units: 'NORAD QRA CF-188 Hornet detachments, Canadian Rangers, Northern Operational Support Hub (NOSH)',
    details: 'Equipped with heavy aircraft hangars and hardened weapons storage to support rapid deployment of fighter jets and surveillance aircraft in the Beaufort Sea.',
    badge: '❄'
  },
  {
    id: 'fol-yellowknife',
    name: 'FOL Yellowknife',
    wing: 'Forward Operating Location',
    designation: 'Central Sub-Arctic NORAD Forward Base',
    branch: 'arctic',
    branchLabel: 'NORAD Arctic Forward Base',
    type: 'Forward Operating Airfield',
    lat: 62.4631,
    lng: -114.4403,
    province: 'Northwest Territories',
    country: 'Canada',
    units: 'NORAD fighter interceptor alert hangars, tactical airlift staging',
    details: 'Maintains hardened hangars and logistical capabilities to stage CF-188 Hornets and maritime patrol aircraft across the central Canadian North.',
    badge: '❄'
  },
  {
    id: 'fol-rankin-inlet',
    name: 'FOL Rankin Inlet',
    wing: 'Hudson Bay Air Defence Facility',
    designation: 'Central Arctic NORAD Forward Operating Location',
    branch: 'arctic',
    branchLabel: 'NORAD Arctic Forward Base',
    type: 'Arctic Interceptor Staging Base',
    lat: 62.8114,
    lng: -92.1158,
    province: 'Nunavut',
    country: 'Canada',
    units: 'NORAD interceptor alert bays, Arctic surveillance staging',
    details: 'Critical interceptor staging hub situated on the northwestern shores of Hudson Bay, defending the central Arctic approaches.',
    badge: '❄'
  },
  {
    id: 'fol-iqaluit',
    name: 'FOL Iqaluit',
    wing: 'Eastern Arctic Air Defence Facility',
    designation: 'Eastern Arctic NORAD Forward Operating Location',
    branch: 'arctic',
    branchLabel: 'NORAD Arctic Forward Base',
    type: 'Eastern Arctic Forward Operating Hub',
    lat: 63.7564,
    lng: -68.5558,
    province: 'Nunavut',
    country: 'Canada',
    units: 'NORAD forward fighter alert hangars, Northern Operational Support Hub (NOSH), Canadian Rangers',
    details: 'Primary forward staging facility in the eastern Arctic, safeguarding the Davis Strait, Baffin Bay, and the Northwest Passage.',
    badge: '❄'
  },
  {
    id: 'fol-kuujjuaq',
    name: 'FOL Kuujjuaq',
    wing: 'Northern Quebec Staging Facility',
    designation: 'Sub-Arctic Staging & Logistic Airfield',
    branch: 'arctic',
    branchLabel: 'Northern Staging Base',
    type: 'Northern Staging Base',
    lat: 58.0961,
    lng: -68.4269,
    province: 'Quebec',
    country: 'Canada',
    units: 'Canadian Rangers, Northern staging detachment, strategic air corridor surveillance',
    details: 'Strategic northern Quebec staging airfield situated near Ungava Bay, supporting Arctic military air corridors and sovereignty exercises.',
    badge: '❄'
  },

  // =========================================================================
  // 6. INTERNATIONAL BASES, OPERATIONAL SUPPORT HUBS (OSH) & NATO MISSIONS
  // =========================================================================
  {
    id: 'camp-adazi-latvia',
    name: 'Camp Ādaži (Op REASSURANCE)',
    wing: 'NATO Multinational Brigade Latvia',
    designation: 'Canada\'s Largest International Combat Deployment',
    branch: 'international',
    branchLabel: 'NATO International Deployment',
    type: 'Multinational Combat Brigade Base',
    lat: 57.0864,
    lng: 24.3314,
    province: 'Ādaži Municipality',
    country: 'Latvia',
    units: 'Task Force Latvia, NATO Multinational Brigade Latvia (Framework Nation: Canada), Canadian Mechanized Battlegroup (1,500 - 2,200 troops)',
    details: 'The centerpiece of Canada\'s international military commitments. Canada serves as the Framework Nation leading NATO\'s combat-ready multinational brigade on the eastern frontier.',
    badge: '🌐'
  },
  {
    id: 'camp-labrie-ceri',
    name: 'Camp Labrie (Ceri Military Complex)',
    wing: 'Task Force Latvia Logistics Base',
    designation: 'Canadian Forces Dedicated Support Base in Latvia',
    branch: 'international',
    branchLabel: 'NATO International Deployment',
    type: 'Permanent Logistics & Housing Base',
    lat: 57.1050,
    lng: 24.3800,
    province: 'Ceri',
    country: 'Latvia',
    units: 'Combat Service Support Company, Canadian Medical Forward Detachment, Brigade Signal Squadron',
    details: 'Modern dedicated Canadian Armed Forces base complex in Latvia, providing operational command, maintenance, and troop housing.',
    badge: '🌐'
  },
  {
    id: 'lielvarde-air-base',
    name: 'Lielvārde Air Base (RCAF Detachment)',
    wing: 'Op REASSURANCE Air Task Force',
    designation: 'RCAF Aviation Task Force Latvia Base',
    branch: 'international',
    branchLabel: 'NATO International Deployment',
    type: 'Combat Aviation Air Base',
    lat: 56.7778,
    lng: 24.8533,
    province: 'Ogre Municipality',
    country: 'Latvia',
    units: 'Air Task Force Latvia (CH-146 Griffon & CH-147F Chinook tactical helicopters)',
    details: 'Operates Canadian Armed Forces rotary-wing tactical aviation assets supporting NATO combat maneuvers across the Baltic region.',
    badge: '🌐'
  },
  {
    id: 'osh-europe-cologne',
    name: 'Operational Support Hub (OSH) Europe',
    wing: 'Cologne-Bonn Air Base',
    designation: 'Strategic European Airlift & Logistics Hub',
    branch: 'international',
    branchLabel: 'International Support Hub',
    type: 'Strategic Logistics Staging Airfield',
    lat: 50.8659,
    lng: 7.1427,
    province: 'North Rhine-Westphalia',
    country: 'Germany',
    units: 'RCAF CC-177 Globemaster / CC-130J staging crews, European Materiel Transit Depot',
    details: 'Canada\'s primary multimodal logistics and personnel hub in Europe, expediting equipment shipments and troop rotations into Eastern Europe and the Middle East.',
    badge: '🌐'
  },
  {
    id: 'det-geilenkirchen',
    name: 'Detachment Geilenkirchen',
    wing: 'NATO Air Base Geilenkirchen',
    designation: 'Canadian Component to NATO Airborne Early Warning',
    branch: 'international',
    branchLabel: 'NATO Component Detachment',
    type: 'NATO E-3A AWACS Air Base',
    lat: 50.9608,
    lng: 6.0428,
    province: 'North Rhine-Westphalia',
    country: 'Germany',
    units: 'Canadian Component NATO E-3A Component (Airborne Early Warning and Control Force)',
    details: 'Long-standing Canadian Armed Forces flight and mission crews flying NATO E-3A Sentry AWACS aircraft providing radar surveillance across NATO borders.',
    badge: '🌐'
  },
  {
    id: 'cfsu-europe-shape',
    name: 'CFSU(E) Casteau / SHAPE',
    wing: 'Supreme HQ Allied Powers Europe',
    designation: 'Canadian Forces Support Unit (Europe) Headquarters',
    branch: 'international',
    branchLabel: 'NATO Strategic Command Support',
    type: 'NATO Strategic Command Support Unit',
    lat: 50.5019,
    lng: 3.9786,
    province: 'Wallonia',
    country: 'Belgium',
    units: 'Canadian Forces Support Unit (Europe), Canadian Military Representative to NATO Military Committee',
    details: 'Provides administrative, communications, and logistical backing for all Canadian Armed Forces personnel assigned across European NATO headquarters.',
    badge: '🌐'
  },
  {
    id: 'osh-southwest-asia',
    name: 'Operational Support Hub (OSH) Southwest Asia',
    wing: 'Ali Al Salem Air Base',
    designation: 'Middle East Operational Staging Hub (Op IMPACT)',
    branch: 'international',
    branchLabel: 'International Support Hub',
    type: 'Middle East Logistics Hub',
    lat: 29.3467,
    lng: 47.5211,
    province: 'Al Jahra',
    country: 'Kuwait',
    units: 'Joint Task Force IMPACT, Tactical Airlift Detachment (CC-130J Hercules), Central Support Element',
    details: 'Central staging base for Canadian operations across the Middle East, supporting Operation IMPACT, capacity-building missions, and UN observer forces.',
    badge: '🌐'
  },
  {
    id: 'camp-canada-iraq',
    name: 'Camp Canada (Union III / Op IMPACT)',
    wing: 'NATO Mission Iraq (NMI)',
    designation: 'Canadian Advisory & Training Mission Base',
    branch: 'international',
    branchLabel: 'International Advisory Mission',
    type: 'Joint Advisory & Training Base',
    lat: 33.2625,
    lng: 44.2344,
    province: 'Baghdad',
    country: 'Iraq',
    units: 'Task Force Middle East, NATO Mission Iraq advisors, Joint Special Operations Task Force',
    details: 'Operational hub for Canadian military advisors providing strategic guidance and institutional military capacity-building in Iraq.',
    badge: '🌐'
  },
  {
    id: 'osh-latin-america',
    name: 'Operational Support Hub (OSH) Latin America & Caribbean',
    wing: 'Kingston Logistics Hub',
    designation: 'Caribbean & Central American Regional Hub',
    branch: 'international',
    branchLabel: 'International Support Hub',
    type: 'Rapid Disaster & Security Hub',
    lat: 17.9356,
    lng: -76.7875,
    province: 'Kingston',
    country: 'Jamaica',
    units: 'Operation CARIBBE forward staging, DART humanitarian disaster response staging element',
    details: 'Provides the Canadian Armed Forces with forward staging capability for counter-narcotics maritime patrols (Op CARIBBE) and hurricane disaster relief.',
    badge: '🌐'
  },
  {
    id: 'osh-west-africa',
    name: 'Operational Support Hub (OSH) West Africa',
    wing: 'Dakar Multimodal Hub',
    designation: 'West African Staging & Diplomatic Airlift Hub',
    branch: 'international',
    branchLabel: 'International Support Hub',
    type: 'Multimodal African Staging Hub',
    lat: 14.7397,
    lng: -17.4902,
    province: 'Dakar',
    country: 'Senegal',
    units: 'Strategic tactical airlift staging, UN peacekeeping mission support element',
    details: 'Enables rapid logistical, medical evacuation, and tactical air transport support for Canadian personnel and UN missions across West and Central Africa.',
    badge: '🌐'
  },
  {
    id: 'norad-hq-peterson',
    name: 'Canadian Detachment - NORAD HQ',
    wing: 'Peterson Space Force Base',
    designation: 'Bi-National Continental Air & Space Defense Command',
    branch: 'international',
    branchLabel: 'NORAD Bi-National Command',
    type: 'Bi-National Strategic Command Base',
    lat: 38.8242,
    lng: -104.7003,
    province: 'Colorado',
    country: 'United States',
    units: 'Canadian NORAD Contingent (Deputy Commander NORAD is a Canadian Lieutenant-General), Cheyenne Mountain Complex',
    details: 'Headquarters of North American Aerospace Defense Command (NORAD) and US Northern Command, co-commanded by senior Canadian general officers.',
    badge: '🌐'
  },
  {
    id: 'conr-tyndall-afb',
    name: 'Canadian Detachment - CONR / 1st Air Force',
    wing: 'Tyndall Air Force Base',
    designation: 'Continental US NORAD Region Canadian Staff',
    branch: 'international',
    branchLabel: 'NORAD Regional Command',
    type: 'Continental Air Defense Command',
    lat: 30.0694,
    lng: -85.5750,
    province: 'Florida',
    country: 'United States',
    units: 'Continental U.S. NORAD Region (CONR) Canadian Operations Officers, WSEP Exercise Element',
    details: 'Houses Canadian military staff officers integrated into the leadership of the Continental United States NORAD Region.',
    badge: '🌐'
  },
  {
    id: 'anr-elmendorf-afb',
    name: 'Canadian Detachment - ANR / 176th ACS',
    wing: 'Joint Base Elmendorf-Richardson (JBER)',
    designation: 'Alaskan NORAD Region Canadian Air Defense Team',
    branch: 'international',
    branchLabel: 'NORAD Regional Command',
    type: 'Arctic Interceptor Control Center',
    lat: 61.2508,
    lng: -149.8069,
    province: 'Alaska',
    country: 'United States',
    units: 'Alaskan NORAD Region (ANR), 176th Air Control Squadron Canadian Mission Commanders & Surveillance Officers',
    details: 'Canadian air battle managers and radar operators serve on active 24/7 watch at JBER monitoring the northern Pacific and Arctic airspace.',
    badge: '🌐'
  },
  {
    id: 'cdls-washington',
    name: 'Canadian Defence Liaison Staff (Washington)',
    wing: 'Canadian Embassy Defense Section',
    designation: 'Canadian Military Diplomatic Mission in the United States',
    branch: 'international',
    branchLabel: 'Military Diplomatic Liaison',
    type: 'Defense Liaison Mission',
    lat: 38.8925,
    lng: -77.0189,
    province: 'District of Columbia',
    country: 'United States',
    units: 'Canadian Defence Attaché, Pentagon Senior Liaison Officers, Inter-American Defense Board delegation',
    details: 'Represents the Chief of the Defence Staff and Minister of National Defence in direct coordination with the Pentagon and US Armed Forces.',
    badge: '🌐'
  },
  {
    id: 'cdls-london',
    name: 'Canadian Defence Liaison Staff (London)',
    wing: 'Canada House / Trafalgar Square',
    designation: 'Canadian Military Mission in the United Kingdom',
    branch: 'international',
    branchLabel: 'Military Diplomatic Liaison',
    type: 'Defense Liaison Mission',
    lat: 51.5076,
    lng: -0.1306,
    province: 'Greater London',
    country: 'United Kingdom',
    units: 'Canadian Defence Adviser to the UK, Ministry of Defence (MOD) senior exchange officers',
    details: 'Historic headquarters coordinating five-eyes defence intelligence, joint military procurement, and bilateral training between Canada and the British Armed Forces.',
    badge: '🌐'
  }
];
