/**
 * CANADIAN CADET ORGANIZATIONS & CANADIAN RANGERS GEOSPATIAL INTELLIGENCE
 * Comprehensive official dataset of:
 * - Royal Canadian Sea Cadets (RCSCC)
 * - Royal Canadian Army Cadets (RCACC)
 * - Royal Canadian Air Cadets (RCACS)
 * - Canadian Ranger Patrols (1, 2, 3, 4 & 5 CRPG)
 * - Junior Canadian Ranger (JCR) Patrols
 * - Cadet Nautical Sites & Sail Training Centres
 * - Cadet Flying Training Centres & Gliding Sites
 * - Summer Cadet Training Centres (CTCs)
 * - Regional Cadet Support Units (RCSU) & National HQ
 */

export const CADETS_AND_RANGERS = [
  // =========================================================================
  // 1. NATIONAL HEADQUARTERS & REGIONAL CADET SUPPORT UNITS (RCSU)
  // =========================================================================
  {
    id: 'rcsu-cjcr-hq',
    name: 'National CJCR Support Group HQ',
    corpsNum: 'HQ',
    type: 'rcsu',
    typeLabel: 'National Headquarters',
    category: 'facility',
    lat: 45.3480,
    lng: -75.8750,
    location: 'Ottawa (NDHQ Carling)',
    province: 'Ontario',
    region: 'National',
    badge: '🏛️',
    details: 'National Headquarters of the Commander, Cadets and Junior Canadian Rangers Support Group (CJCR). Coordinates youth leadership development and cadet movements coast-to-coast.'
  },
  {
    id: 'rcsu-atlantic',
    name: 'RCSU (Atlantic) Headquarters',
    corpsNum: 'RCSU-A',
    type: 'rcsu',
    typeLabel: 'Regional Cadet Support Unit',
    category: 'facility',
    lat: 44.6390,
    lng: -63.5130,
    location: '12 Wing Shearwater / Halifax',
    province: 'Nova Scotia',
    region: 'Atlantic',
    badge: '🏛️',
    details: 'Regional Cadet Support Unit (Atlantic). Delivers and oversees Sea, Army, and Air Cadet operations across Nova Scotia, New Brunswick, Prince Edward Island, and Newfoundland & Labrador.'
  },
  {
    id: 'rcsu-eastern',
    name: 'RCSU (Eastern) Headquarters',
    corpsNum: 'RCSU-E',
    type: 'rcsu',
    typeLabel: 'Regional Cadet Support Unit',
    category: 'facility',
    lat: 45.3020,
    lng: -73.2750,
    location: 'CFB Saint-Jean / Montreal',
    province: 'Quebec',
    region: 'Eastern',
    badge: '🏛️',
    details: 'Regional Cadet Support Unit (Eastern). Manages Cadet and JCR programs throughout Quebec and the Ottawa Valley region.'
  },
  {
    id: 'rcsu-central',
    name: 'RCSU (Central) Headquarters',
    corpsNum: 'RCSU-C',
    type: 'rcsu',
    typeLabel: 'Regional Cadet Support Unit',
    category: 'facility',
    lat: 44.2700,
    lng: -79.9100,
    location: 'CFB Borden',
    province: 'Ontario',
    region: 'Central',
    badge: '🏛️',
    details: 'Regional Cadet Support Unit (Central). Administers and provides command support for hundreds of cadet corps and squadrons across Ontario.'
  },
  {
    id: 'rcsu-northwest',
    name: 'RCSU (Northwest) Headquarters',
    corpsNum: 'RCSU-NW',
    type: 'rcsu',
    typeLabel: 'Regional Cadet Support Unit',
    category: 'facility',
    lat: 49.9050,
    lng: -97.2400,
    location: '17 Wing Winnipeg',
    province: 'Manitoba',
    region: 'Northwest',
    badge: '🏛️',
    details: 'Regional Cadet Support Unit (Northwest). Oversees Sea, Army, and Air Cadets across Manitoba, Saskatchewan, Alberta, Yukon, Northwest Territories, and Nunavut.'
  },
  {
    id: 'rcsu-pacific',
    name: 'RCSU (Pacific) Headquarters',
    corpsNum: 'RCSU-P',
    type: 'rcsu',
    typeLabel: 'Regional Cadet Support Unit',
    category: 'facility',
    lat: 48.4350,
    lng: -123.4250,
    location: 'CFB Esquimalt / Victoria',
    province: 'British Columbia',
    region: 'Pacific',
    badge: '🏛️',
    details: 'Regional Cadet Support Unit (Pacific). Manages all Cadet training formations, sailing sites, and gliding wings across British Columbia.'
  },

  // =========================================================================
  // 2. CADET TRAINING CENTRES (SUMMER CTCs)
  // =========================================================================
  {
    id: 'ctc-argonaut',
    name: 'Argonaut Cadet Training Centre',
    corpsNum: 'CTC',
    type: 'ctc',
    typeLabel: 'Cadet Training Centre (CTC)',
    category: 'ctc',
    lat: 45.8200,
    lng: -66.4400,
    location: '5 CDSB Gagetown, Oromocto',
    province: 'New Brunswick',
    region: 'Atlantic',
    badge: '🏕️',
    details: 'Premier Atlantic summer cadet training centre. Provides advanced leadership, expedition, pipes & drums, drill & ceremonial, and marksmanship courses for thousands of cadets annually.'
  },
  {
    id: 'ctc-greenwood',
    name: 'Greenwood Cadet Training Centre',
    corpsNum: 'CTC',
    type: 'ctc',
    typeLabel: 'Cadet Training Centre (CTC)',
    category: 'ctc',
    lat: 44.9750,
    lng: -64.9180,
    location: '14 Wing Greenwood',
    province: 'Nova Scotia',
    region: 'Atlantic',
    badge: '🏕️',
    details: 'Air Cadet summer training centre hosting aviation technology, aerospace, airport operations, military band, and leadership training.'
  },
  {
    id: 'ctc-valcartier',
    name: 'Valcartier Cadet Training Centre',
    corpsNum: 'CTC',
    type: 'ctc',
    typeLabel: 'Cadet Training Centre (CTC)',
    category: 'ctc',
    lat: 46.8850,
    lng: -71.4920,
    location: 'CFB Valcartier, Saint-Gabriel-de-Valcartier',
    province: 'Quebec',
    region: 'Eastern',
    badge: '🏕️',
    details: 'Major bilingual cadet training centre located at 2nd Canadian Division Support Base Valcartier. Focuses on field expedition, sports & fitness, and leadership.'
  },
  {
    id: 'ctc-bagotville',
    name: 'Bagotville Cadet Training Centre',
    corpsNum: 'CTC',
    type: 'ctc',
    typeLabel: 'Cadet Training Centre (CTC)',
    category: 'ctc',
    lat: 48.3300,
    lng: -71.0000,
    location: '3 Wing Bagotville, Saguenay',
    province: 'Quebec',
    region: 'Eastern',
    badge: '🏕️',
    details: 'Air Cadet aviation training centre at Canada\'s eastern tactical fighter wing. Specializes in aviation fundamentals, flight line operations, and military aviation.'
  },
  {
    id: 'ctc-blackdown',
    name: 'Blackdown Cadet Training Centre',
    corpsNum: 'CTC',
    type: 'ctc',
    typeLabel: 'Cadet Training Centre (CTC)',
    category: 'ctc',
    lat: 44.2880,
    lng: -79.9250,
    location: 'CFB Borden',
    province: 'Ontario',
    region: 'Central',
    badge: '🏕️',
    details: 'Largest cadet training centre in Canada, hosting over 3,000 cadets and staff every summer. Comprehensive tri-service training in military band, pipes & drums, survival, athletics, and drill.'
  },
  {
    id: 'ctc-trenton',
    name: 'Trenton Cadet Training Centre',
    corpsNum: 'CTC',
    type: 'ctc',
    typeLabel: 'Cadet Training Centre (CTC)',
    category: 'ctc',
    lat: 44.1180,
    lng: -77.5280,
    location: '8 Wing Trenton, Astra',
    province: 'Ontario',
    region: 'Central',
    badge: '🏕️',
    details: 'Aviation and aerospace training hub at Canada\'s premier airlift base. Courses include introduction to aviation, aerospace sciences, and air traffic control fundamentals.'
  },
  {
    id: 'ctc-connaught',
    name: 'Connaught Cadet Training Centre',
    corpsNum: 'CTC',
    type: 'ctc',
    typeLabel: 'Cadet Training Centre (CTC)',
    category: 'ctc',
    lat: 45.3670,
    lng: -75.8970,
    location: 'Connaught Range, Ottawa',
    province: 'Ontario',
    region: 'Central',
    badge: '🏕️',
    details: 'National centre of excellence for cadet marksmanship. Home of the National Cadet Fullbore Marksmanship Course (DCRA) and international rifle exchanges.'
  },
  {
    id: 'ctc-gimli',
    name: 'Gimli Cadet Flying Training Centre',
    corpsNum: 'CTC',
    type: 'ctc',
    typeLabel: 'Cadet Training Centre (CTC)',
    category: 'ctc',
    lat: 50.6290,
    lng: -97.0420,
    location: 'Gimli Industrial Park Airport',
    province: 'Manitoba',
    region: 'Northwest',
    badge: '🏕️',
    details: 'Historic flight school base hosting the Central and Northwest Region Glider Pilot Training Scholarship and Power Pilot Scholarship programs.'
  },
  {
    id: 'ctc-cold-lake',
    name: 'Cold Lake Cadet Training Centre',
    corpsNum: 'CTC',
    type: 'ctc',
    typeLabel: 'Cadet Training Centre (CTC)',
    category: 'ctc',
    lat: 54.4050,
    lng: -110.2800,
    location: '4 Wing Cold Lake',
    province: 'Alberta',
    region: 'Northwest',
    badge: '🏕️',
    details: 'Western fighter wing training camp hosting leadership, survival, aerospace, and aviation mechanics courses alongside CF-18 squadrons.'
  },
  {
    id: 'ctc-rocky-mountain',
    name: 'Rocky Mountain Cadet Training Centre',
    corpsNum: 'CTC',
    type: 'ctc',
    typeLabel: 'Cadet Training Centre (CTC)',
    category: 'ctc',
    lat: 51.2750,
    lng: -114.9850,
    location: 'Ghost River / Cochrane',
    province: 'Alberta',
    region: 'Northwest',
    badge: '🏕️',
    details: 'Premier alpine and wilderness leadership camp situated in the foothills of the Canadian Rockies. Specializes in advanced mountain trekking, white-water kayaking, and glacier navigation.'
  },
  {
    id: 'ctc-vernon',
    name: 'Vernon Cadet Training Centre',
    corpsNum: 'CTC',
    type: 'ctc',
    typeLabel: 'Cadet Training Centre (CTC)',
    category: 'ctc',
    lat: 50.2520,
    lng: -119.2850,
    location: 'Vernon Military Camp, Okanagan',
    province: 'British Columbia',
    region: 'Pacific',
    badge: '🏕️',
    details: 'Western Canada\'s oldest continuous training facility (established 1949). Delivers expedition, sports and fitness, military band, and marksmanship courses in the Okanagan Valley.'
  },
  {
    id: 'ctc-hmcs-quadra',
    name: 'HMCS Quadra Cadet Training Centre',
    corpsNum: 'CTC',
    type: 'ctc',
    typeLabel: 'Cadet Training Centre (CTC)',
    category: 'ctc',
    lat: 49.6600,
    lng: -124.9080,
    location: 'Goose Spit, Comox',
    province: 'British Columbia',
    region: 'Pacific',
    badge: '🏕️',
    details: 'Canada\'s primary Sea Cadet training establishment on Vancouver Island. Delivers advanced sail training, naval communications, ship\'s boat operator, navigation, and marine engineering.'
  },
  {
    id: 'ctc-whitehorse',
    name: 'Whitehorse Cadet Training Centre',
    corpsNum: 'CTC',
    type: 'ctc',
    typeLabel: 'Cadet Training Centre (CTC)',
    category: 'ctc',
    lat: 60.7100,
    lng: -135.0600,
    location: 'Whitehorse',
    province: 'Yukon',
    region: 'North',
    badge: '🏕️',
    details: 'Northern territorial summer training centre conducting northern expedition training, wilderness bushcraft, and JCR leader courses.'
  },

  // =========================================================================
  // 3. CADET NAUTICAL SITES & SAIL TRAINING CENTRES
  // =========================================================================
  {
    id: 'cns-shearwater',
    name: 'Cadet Nautical Site Shearwater',
    corpsNum: 'CNS',
    type: 'nautical_site',
    typeLabel: 'Cadet Nautical Site',
    category: 'nautical',
    lat: 44.6410,
    lng: -63.5200,
    location: 'Shearwater / Halifax Harbour',
    province: 'Nova Scotia',
    region: 'Atlantic',
    badge: '⛵',
    details: 'East Coast tactical waterborne sail and seamanship training facility operating CL-16 dinghies, whalers, and Zodiac power craft in Halifax Harbour.'
  },
  {
    id: 'cns-hmcs-acadia',
    name: 'Cadet Nautical Training Site Acadia',
    corpsNum: 'CNS',
    type: 'nautical_site',
    typeLabel: 'Cadet Nautical Site',
    category: 'nautical',
    lat: 44.6250,
    lng: -65.7350,
    location: 'Cornwallis, Annapolis Basin',
    province: 'Nova Scotia',
    region: 'Atlantic',
    badge: '⛵',
    details: 'Dedicated tidal training centre on the Annapolis Basin for ocean sailing, coastal navigation, and coxswain qualifications.'
  },
  {
    id: 'cns-saint-john',
    name: 'Cadet Nautical Site Saint John',
    corpsNum: 'CNS',
    type: 'nautical_site',
    typeLabel: 'Cadet Nautical Site',
    category: 'nautical',
    lat: 45.3120,
    lng: -66.0250,
    location: 'Kennebecasis River, Renforth',
    province: 'New Brunswick',
    region: 'Atlantic',
    badge: '⛵',
    details: 'Regional sailing site providing CanSail certification and small-craft safety for New Brunswick naval cadets.'
  },
  {
    id: 'cns-corner-brook',
    name: 'Cadet Nautical Site Bay of Islands',
    corpsNum: 'CNS',
    type: 'nautical_site',
    typeLabel: 'Cadet Nautical Site',
    category: 'nautical',
    lat: 48.9550,
    lng: -57.9620,
    location: 'Bay of Islands, Corner Brook',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '⛵',
    details: 'Western Newfoundland nautical training hub for RCSCC 194 Bonaventure and visiting western cadet corps.'
  },
  {
    id: 'cns-deer-lake',
    name: 'Cadet Nautical Site Deer Lake',
    corpsNum: 'CNS',
    type: 'nautical_site',
    typeLabel: 'Cadet Nautical Site',
    category: 'nautical',
    lat: 49.1700,
    lng: -57.4350,
    location: 'Deer Lake Waterway, Humber Valley',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '⛵',
    details: 'Water training site supporting RCSCC 328 Atlantic on Deer Lake with sailing dinghies and safety cutter vessels.'
  },
  {
    id: 'cns-st-johns',
    name: 'Cadet Nautical Site St. John\'s Harbour',
    corpsNum: 'CNS',
    type: 'nautical_site',
    typeLabel: 'Cadet Nautical Site',
    category: 'nautical',
    lat: 47.5680,
    lng: -52.7050,
    location: 'Southside Road, St. John\'s',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '⛵',
    details: 'Eastern Newfoundland naval training site for RCSCC 166 Fort Townshend in historic St. John\'s harbour.'
  },
  {
    id: 'cns-pointe-claire',
    name: 'Cadet Nautical Site Pointe-Claire',
    corpsNum: 'CNS',
    type: 'nautical_site',
    typeLabel: 'Cadet Nautical Site',
    category: 'nautical',
    lat: 45.4280,
    lng: -73.8250,
    location: 'Lac Saint-Louis, Montreal',
    province: 'Quebec',
    region: 'Eastern',
    badge: '⛵',
    details: 'Major freshwater sail training facility for the Greater Montreal area on the St. Lawrence River / Lake Saint-Louis.'
  },
  {
    id: 'cns-kingston-ontario',
    name: 'HMCS Ontario Cadet Nautical Centre',
    corpsNum: 'CNS',
    type: 'nautical_site',
    typeLabel: 'Cadet Nautical Site',
    category: 'nautical',
    lat: 44.2250,
    lng: -76.5150,
    location: 'Portsmouth Olympic Harbour, Kingston',
    province: 'Ontario',
    region: 'Central',
    badge: '⛵',
    details: 'Historic Olympic harbour sailing school on Lake Ontario. Conducts CanSail 1-4 certification and fleet regattas.'
  },
  {
    id: 'cns-barrie',
    name: 'Cadet Nautical Site Kempenfelt Bay',
    corpsNum: 'CNS',
    type: 'nautical_site',
    typeLabel: 'Cadet Nautical Site',
    category: 'nautical',
    lat: 44.3850,
    lng: -79.6800,
    location: 'Lake Simcoe, Barrie',
    province: 'Ontario',
    region: 'Central',
    badge: '⛵',
    details: 'Central region sail centre hosting weekend sailing familiarization and seamanship exercises on Lake Simcoe.'
  },
  {
    id: 'cns-gimli',
    name: 'Cadet Nautical Site Gimli',
    corpsNum: 'CNS',
    type: 'nautical_site',
    typeLabel: 'Cadet Nautical Site',
    category: 'nautical',
    lat: 50.6310,
    lng: -96.9850,
    location: 'Lake Winnipeg, Gimli',
    province: 'Manitoba',
    region: 'Northwest',
    badge: '⛵',
    details: 'Prairie inland sea sail training facility on Lake Winnipeg, supporting sea cadets from across Manitoba and Saskatchewan.'
  },
  {
    id: 'cns-calgary',
    name: 'Cadet Nautical Site Glenmore',
    corpsNum: 'CNS',
    type: 'nautical_site',
    typeLabel: 'Cadet Nautical Site',
    category: 'nautical',
    lat: 50.9850,
    lng: -114.1100,
    location: 'Glenmore Reservoir, Calgary',
    province: 'Alberta',
    region: 'Northwest',
    badge: '⛵',
    details: 'Southern Alberta sail centre training RCSCC 93 Undaunted and prairie sea cadet corps in dinghy handling and boatmanship.'
  },
  {
    id: 'cns-jericho-vancouver',
    name: 'Cadet Nautical Site Jericho Beach',
    corpsNum: 'CNS',
    type: 'nautical_site',
    typeLabel: 'Cadet Nautical Site',
    category: 'nautical',
    lat: 49.2740,
    lng: -123.1950,
    location: 'English Bay, Vancouver',
    province: 'British Columbia',
    region: 'Pacific',
    badge: '⛵',
    details: 'Premier West Coast salt-water sail training centre in English Bay with immediate ocean access for Pacific sea cadets.'
  },

  // =========================================================================
  // 4. CADET FLYING SITES & GLIDING CENTRES
  // =========================================================================
  {
    id: 'cfs-debert',
    name: 'Debert Cadet Flying Training Centre',
    corpsNum: 'CFS',
    type: 'flying_site',
    typeLabel: 'Cadet Flying & Gliding Site',
    category: 'flying',
    lat: 45.4180,
    lng: -63.4620,
    location: 'Debert Aerodrome (CCQ3)',
    province: 'Nova Scotia',
    region: 'Atlantic',
    badge: '🛩️',
    details: 'Primary Regional Cadet Air Operations hub for Atlantic Canada. Operates Schweitzer SGS 2-33A gliders and Bellanca Scout tow planes.'
  },
  {
    id: 'cfs-gander',
    name: 'Cadet Gliding Site Gander',
    corpsNum: 'CFS',
    type: 'flying_site',
    typeLabel: 'Cadet Flying & Gliding Site',
    category: 'flying',
    lat: 48.9400,
    lng: -54.5680,
    location: 'Gander International Airport (CYQX)',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '🛩️',
    details: 'Central Newfoundland cadet gliding operations centre hosting spring and autumn familiarization flying flights.'
  },
  {
    id: 'cfs-stephenville',
    name: 'Cadet Gliding Site Stephenville',
    corpsNum: 'CFS',
    type: 'flying_site',
    typeLabel: 'Cadet Flying & Gliding Site',
    category: 'flying',
    lat: 48.5440,
    lng: -58.5500,
    location: 'Stephenville Airport (CYJT)',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '🛩️',
    details: 'Western Newfoundland cadet soaring site for squadrons across Deer Lake, Corner Brook, and St. George\'s.'
  },
  {
    id: 'cfs-bell-island',
    name: 'Cadet Gliding Site Bell Island',
    corpsNum: 'CFS',
    type: 'flying_site',
    typeLabel: 'Cadet Flying & Gliding Site',
    category: 'flying',
    lat: 47.6350,
    lng: -52.9800,
    location: 'Bell Island Airstrip (CCV4)',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '🛩️',
    details: 'Eastern Newfoundland glider site providing soaring experience over Conception Bay for Avalon Peninsula air cadets.'
  },
  {
    id: 'cfs-st-jean',
    name: 'Saint-Jean Cadet Gliding Centre',
    corpsNum: 'CFS',
    type: 'flying_site',
    typeLabel: 'Cadet Flying & Gliding Site',
    category: 'flying',
    lat: 45.2950,
    lng: -73.2810,
    location: 'Saint-Jean Aerodrome (CYJN)',
    province: 'Quebec',
    region: 'Eastern',
    badge: '🛩️',
    details: 'HQ of Eastern Region Cadet Air Operations. Directs gliding wings throughout Quebec and hosts the Glider Pilot Scholarship.'
  },
  {
    id: 'cfs-mountain-view',
    name: 'Mountain View Cadet Flying Centre',
    corpsNum: 'CFS',
    type: 'flying_site',
    typeLabel: 'Cadet Flying & Gliding Site',
    category: 'flying',
    lat: 44.0750,
    lng: -77.3400,
    location: 'CFB Trenton Detachment Mountain View',
    province: 'Ontario',
    region: 'Central',
    badge: '🛩️',
    details: 'Central Region\'s premier soaring aerodrome. Houses the maintenance depot for cadet gliders and aircraft tow-planes.'
  },
  {
    id: 'cfs-borden',
    name: 'Cadet Gliding Site Borden',
    corpsNum: 'CFS',
    type: 'flying_site',
    typeLabel: 'Cadet Flying & Gliding Site',
    category: 'flying',
    lat: 44.2720,
    lng: -79.9120,
    location: 'CFB Borden Airfield',
    province: 'Ontario',
    region: 'Central',
    badge: '🛩️',
    details: 'Simcoe County soaring airfield providing continuous spring and fall familiarization launches for GTA and Central Ontario cadets.'
  },
  {
    id: 'cfs-netook',
    name: 'Netook Cadet Gliding Centre',
    corpsNum: 'CFS',
    type: 'flying_site',
    typeLabel: 'Cadet Flying & Gliding Site',
    category: 'flying',
    lat: 51.8480,
    lng: -114.1080,
    location: 'Olds-Netook Airport (CFK6)',
    province: 'Alberta',
    region: 'Northwest',
    badge: '🛩️',
    details: 'Northwest Region Cadet Flying Operations centre. Major glider flight training centre between Calgary and Red Deer.'
  },
  {
    id: 'cfs-pitt-meadows',
    name: 'Cadet Gliding Site Pitt Meadows',
    corpsNum: 'CFS',
    type: 'flying_site',
    typeLabel: 'Cadet Flying & Gliding Site',
    category: 'flying',
    lat: 49.2160,
    lng: -122.7100,
    location: 'Pitt Meadows Regional Airport (CYPK)',
    province: 'British Columbia',
    region: 'Pacific',
    badge: '🛩️',
    details: 'Lower Mainland glider hub serving dozens of Vancouver, Fraser Valley, and North Shore air cadet squadrons.'
  },
  {
    id: 'cfs-comox',
    name: 'Comox Cadet Flying Centre',
    corpsNum: 'CFS',
    type: 'flying_site',
    typeLabel: 'Cadet Flying & Gliding Site',
    category: 'flying',
    lat: 49.7100,
    lng: -124.8860,
    location: '19 Wing Comox Airfield (CYQQ)',
    province: 'British Columbia',
    region: 'Pacific',
    badge: '🛩️',
    details: 'Pacific Region Cadet Air Operations headquarters. Conducts glider and powered flight training along Georgia Strait.'
  },

  // =========================================================================
  // 5. CANADIAN RANGER PATROLS (CRP) - ALL 5 PATROL GROUPS
  // =========================================================================
  // --- 1st Canadian Ranger Patrol Group (1 CRPG - Territories & North) ---
  {
    id: 'crp-yellowknife',
    name: '1 CRPG Headquarters & Yellowknife Patrol',
    corpsNum: '1 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 62.4540,
    lng: -114.3718,
    location: 'Yellowknife',
    province: 'Northwest Territories',
    region: 'North',
    badge: '🪓',
    details: 'Headquarters of the 1st Canadian Ranger Patrol Group, commanding 60+ patrols covering 40% of Canada\'s landmass across NT, Nunavut, and Yukon.'
  },
  {
    id: 'crp-inuvik',
    name: 'Inuvik Canadian Ranger Patrol',
    corpsNum: '1 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 68.3607,
    lng: -133.7230,
    location: 'Inuvik, Mackenzie Delta',
    province: 'Northwest Territories',
    region: 'North',
    badge: '🪓',
    details: 'Strategic northern delta patrol conducting Arctic winter sovereign mobility surveillance along the Dempster Highway and Beaufort Sea coast.'
  },
  {
    id: 'crp-cambridge-bay',
    name: 'Cambridge Bay Canadian Ranger Patrol',
    corpsNum: '1 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 69.1170,
    lng: -105.0530,
    location: 'Cambridge Bay, Victoria Island',
    province: 'Nunavut',
    region: 'North',
    badge: '🪓',
    details: 'Northwest Passage central surveillance outpost based beside the Canadian High Arctic Research Station (CHARS).'
  },
  {
    id: 'crp-iqaluit',
    name: 'Iqaluit Canadian Ranger Patrol',
    corpsNum: '1 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 63.7467,
    lng: -68.5170,
    location: 'Iqaluit, Baffin Island',
    province: 'Nunavut',
    region: 'North',
    badge: '🪓',
    details: 'Capital patrol of Nunavut on Frobisher Bay. Provides immediate territorial search and rescue and ground reconnaissance for Operation NANOOK.'
  },
  {
    id: 'crp-resolute-bay',
    name: 'Resolute Bay Canadian Ranger Patrol',
    corpsNum: '1 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 74.6975,
    lng: -94.8297,
    location: 'Resolute Bay, Cornwallis Island',
    province: 'Nunavut',
    region: 'North',
    badge: '🪓',
    details: 'Home of the Canadian Armed Forces Arctic Training Centre (CAFATC). Provides extreme cold weather survival instruction and Parry Channel surveillance.'
  },
  {
    id: 'crp-grise-fiord',
    name: 'Grise Fiord Canadian Ranger Patrol',
    corpsNum: '1 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 76.4190,
    lng: -82.8950,
    location: 'Grise Fiord, Ellesmere Island',
    province: 'Nunavut',
    region: 'North',
    badge: '🪓',
    details: 'Canada\'s northernmost civilian community patrol. Conducts long-distance polar bear tracking, sovereign reconnaissance, and patrols towards CFS Alert.'
  },
  {
    id: 'crp-dawson-city',
    name: 'Dawson City Canadian Ranger Patrol',
    corpsNum: '1 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 64.0600,
    lng: -139.4320,
    location: 'Dawson City, Klondike',
    province: 'Yukon',
    region: 'North',
    badge: '🪓',
    details: 'Historic gold rush junction patrol monitoring northern Yukon river valleys and mountainous wilderness corridors.'
  },
  {
    id: 'crp-atlin',
    name: 'Atlin Canadian Ranger Patrol',
    corpsNum: '1 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 59.5750,
    lng: -133.6980,
    location: 'Atlin',
    province: 'British Columbia',
    region: 'North',
    badge: '🪓',
    details: 'Sub-Arctic northern BC patrol administered by 1 CRPG due to geographic alignment with the Yukon border.'
  },

  // --- 2nd Canadian Ranger Patrol Group (2 CRPG - Northern Quebec & Nunavik) ---
  {
    id: 'crp-kuujjuaq',
    name: 'Kuujjuaq Canadian Ranger Patrol',
    corpsNum: '2 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 58.1030,
    lng: -68.4120,
    location: 'Kuujjuaq, Koksoak River',
    province: 'Quebec',
    region: 'Eastern',
    badge: '🪓',
    details: 'Regional command hub for Nunavik Inuit rangers. Conducts coastal and inland tundra patrols connecting Ungava Bay communities.'
  },
  {
    id: 'crp-salluit',
    name: 'Salluit Canadian Ranger Patrol',
    corpsNum: '2 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 62.2030,
    lng: -75.6420,
    location: 'Salluit, Hudson Strait',
    province: 'Quebec',
    region: 'Eastern',
    badge: '🪓',
    details: 'Northern tip of Quebec on the Hudson Strait. Crucial observers of northern maritime sea lanes and ice conditions.'
  },
  {
    id: 'crp-blanc-sablon',
    name: 'Blanc-Sablon Canadian Ranger Patrol',
    corpsNum: '2 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 51.4250,
    lng: -57.1350,
    location: 'Blanc-Sablon, Lower North Shore',
    province: 'Quebec',
    region: 'Eastern',
    badge: '🪓',
    details: 'Guards the eastern gateway to the Strait of Belle Isle immediately adjacent to the Labrador border.'
  },

  // --- 3rd Canadian Ranger Patrol Group (3 CRPG - Northern Ontario) ---
  {
    id: 'crp-moosonee',
    name: 'Moosonee & Moose Factory Patrol',
    corpsNum: '3 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 51.2720,
    lng: -80.6430,
    location: 'James Bay, Moosonee',
    province: 'Ontario',
    region: 'Central',
    badge: '🪓',
    details: 'James Bay command node for 3 CRPG. Frequently activated for seasonal flood evacuations, ice monitoring, and search & rescue.'
  },
  {
    id: 'crp-fort-severn',
    name: 'Fort Severn Canadian Ranger Patrol',
    corpsNum: '3 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 56.0020,
    lng: -87.6250,
    location: 'Fort Severn First Nation, Hudson Bay',
    province: 'Ontario',
    region: 'Central',
    badge: '🪓',
    details: 'Northernmost community in Ontario, situated on the south shore of Hudson Bay.'
  },
  {
    id: 'crp-attawapiskat',
    name: 'Attawapiskat Canadian Ranger Patrol',
    corpsNum: '3 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 52.9280,
    lng: -82.4300,
    location: 'Attawapiskat, James Bay Coast',
    province: 'Ontario',
    region: 'Central',
    badge: '🪓',
    details: 'Coastal Cree community patrol highly skilled in sub-arctic winter travel and wilderness lifesaving.'
  },
  {
    id: 'crp-sandy-lake',
    name: 'Sandy Lake Canadian Ranger Patrol',
    corpsNum: '3 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 53.8600,
    lng: -93.3400,
    location: 'Sandy Lake First Nation',
    province: 'Ontario',
    region: 'Central',
    badge: '🪓',
    details: 'Isolated northwestern Ontario community patrol providing essential search and rescue in dense boreal forest.'
  },

  // --- 4th Canadian Ranger Patrol Group (4 CRPG - Western Provinces) ---
  {
    id: 'crp-churchill',
    name: 'Churchill Canadian Ranger Patrol',
    corpsNum: '4 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 58.7680,
    lng: -94.1650,
    location: 'Churchill, Hudson Bay Port',
    province: 'Manitoba',
    region: 'Northwest',
    badge: '🪓',
    details: 'Guards Canada\'s only deep-water Arctic seaport on Hudson Bay. Operates in extreme weather and polar bear territory.'
  },
  {
    id: 'crp-prince-rupert',
    name: 'Prince Rupert Canadian Ranger Patrol',
    corpsNum: '4 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 54.3150,
    lng: -130.3200,
    location: 'Prince Rupert, North Coast',
    province: 'British Columbia',
    region: 'Pacific',
    badge: '🪓',
    details: 'Coastal patrol safeguarding the northern Pacific shipping approaches, Alaskan border, and Hecate Strait.'
  },
  {
    id: 'crp-haida-gwaii',
    name: 'Haida Gwaii Canadian Ranger Patrol',
    corpsNum: '4 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 53.2500,
    lng: -132.0000,
    location: 'Daajing Giids / Masset',
    province: 'British Columbia',
    region: 'Pacific',
    badge: '🪓',
    details: 'Offshore archipelago patrol conducting maritime sovereignty watches along Canada\'s westernmost maritime perimeter.'
  },

  // --- 5th Canadian Ranger Patrol Group (5 CRPG - Newfoundland & Labrador) ---
  {
    id: 'crp-5crpg-hq-gander',
    name: '5 CRPG Headquarters Gander',
    corpsNum: '5 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol HQ',
    category: 'ranger',
    lat: 48.9550,
    lng: -54.6080,
    location: '9 Wing Gander',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '🪓',
    details: 'Headquarters of the 5th Canadian Ranger Patrol Group, commanding 32 patrols across Newfoundland and coastal Labrador.'
  },
  {
    id: 'crp-nain',
    name: 'Nain Canadian Ranger Patrol',
    corpsNum: '5 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 56.5420,
    lng: -61.6910,
    location: 'Nain, Nunatsiavut',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '🪓',
    details: 'Administrative capital of Nunatsiavut and the northernmost permanent settlement in Newfoundland and Labrador.'
  },
  {
    id: 'crp-hopedale',
    name: 'Hopedale Canadian Ranger Patrol',
    corpsNum: '5 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 55.4580,
    lng: -60.2180,
    location: 'Hopedale, Labrador Coast',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '🪓',
    details: 'Legislative capital of Nunatsiavut. Crucial coastal ice observers and winter overland reconnaissance.'
  },
  {
    id: 'crp-happy-valley-goose-bay',
    name: 'Goose Bay Canadian Ranger Patrol',
    corpsNum: '5 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 53.3010,
    lng: -60.3260,
    location: 'Happy Valley-Goose Bay',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '🪓',
    details: 'Central Labrador operational hub supporting 5 Wing and wilderness tactical search & rescue across central Labrador.'
  },
  {
    id: 'crp-st-anthony',
    name: 'St. Anthony Canadian Ranger Patrol',
    corpsNum: '5 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 51.3710,
    lng: -55.5960,
    location: 'St. Anthony, Northern Peninsula',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '🪓',
    details: 'Northern tip of Newfoundland monitoring the Strait of Belle Isle, icebergs, and northern coastal approaches.'
  },
  {
    id: 'crp-port-saunders',
    name: 'Port Saunders Canadian Ranger Patrol',
    corpsNum: '5 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 50.6400,
    lng: -57.3000,
    location: 'Port Saunders / Hawkes Bay',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '🪓',
    details: 'Western coastal patrol covering the Gulf of St. Lawrence coastline and Long Range Mountains.'
  },
  {
    id: 'crp-cartwright',
    name: 'Cartwright Canadian Ranger Patrol',
    corpsNum: '5 CRPG',
    type: 'ranger_patrol',
    typeLabel: 'Canadian Ranger Patrol',
    category: 'ranger',
    lat: 53.7050,
    lng: -57.0150,
    location: 'Cartwright, Sandwich Bay',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '🪓',
    details: 'Southern Labrador coastal community guarding Sandwich Bay approaches and providing emergency trail recovery.'
  },

  // =========================================================================
  // 6. JUNIOR CANADIAN RANGER (JCR) PATROLS
  // =========================================================================
  {
    id: 'jcr-nain',
    name: 'JCR Nain Patrol',
    corpsNum: 'JCR',
    type: 'jcr_patrol',
    typeLabel: 'Junior Canadian Rangers',
    category: 'ranger',
    lat: 56.5400,
    lng: -61.6850,
    location: 'Nain, Nunatsiavut',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '🌲',
    details: 'Active youth development program teaching traditional Inuit survival skills, marksmanship, snowmobile mechanics, and community leadership.'
  },
  {
    id: 'jcr-hopedale',
    name: 'JCR Hopedale Patrol',
    corpsNum: 'JCR',
    type: 'jcr_patrol',
    typeLabel: 'Junior Canadian Rangers',
    category: 'ranger',
    lat: 55.4550,
    lng: -60.2220,
    location: 'Hopedale',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '🌲',
    details: 'Labrador coastal youth patrol mentored by Canadian Ranger adults in life skills and northern tradition.'
  },
  {
    id: 'jcr-kuujjuaq',
    name: 'JCR Kuujjuaq Patrol',
    corpsNum: 'JCR',
    type: 'jcr_patrol',
    typeLabel: 'Junior Canadian Rangers',
    category: 'ranger',
    lat: 58.1060,
    lng: -68.4100,
    location: 'Kuujjuaq',
    province: 'Quebec',
    region: 'Eastern',
    badge: '🌲',
    details: 'Nunavik JCR patrol developing young leaders in northern Quebec, participating in annual provincial gatherings.'
  },
  {
    id: 'jcr-attawapiskat',
    name: 'JCR Attawapiskat Patrol',
    corpsNum: 'JCR',
    type: 'jcr_patrol',
    typeLabel: 'Junior Canadian Rangers',
    category: 'ranger',
    lat: 52.9250,
    lng: -82.4250,
    location: 'Attawapiskat, James Bay',
    province: 'Ontario',
    region: 'Central',
    badge: '🌲',
    details: '3 CRPG mentored youth patrol on James Bay coast fostering First Nations cultural heritage, outdoor survival, and first aid.'
  },
  {
    id: 'jcr-iqaluit',
    name: 'JCR Iqaluit Patrol',
    corpsNum: 'JCR',
    type: 'jcr_patrol',
    typeLabel: 'Junior Canadian Rangers',
    category: 'ranger',
    lat: 63.7490,
    lng: -68.5210,
    location: 'Iqaluit, Baffin Island',
    province: 'Nunavut',
    region: 'North',
    badge: '🌲',
    details: 'Territorial capital JCR patrol learning navigation, firearms safety, and winter search operations.'
  },
  {
    id: 'jcr-inuvik',
    name: 'JCR Inuvik Patrol',
    corpsNum: 'JCR',
    type: 'jcr_patrol',
    typeLabel: 'Junior Canadian Rangers',
    category: 'ranger',
    lat: 68.3580,
    lng: -133.7190,
    location: 'Inuvik',
    province: 'Northwest Territories',
    region: 'North',
    badge: '🌲',
    details: 'Mackenzie Delta JCR group teaching arctic camping, ice safety, hunting traditions, and public speaking.'
  },

  // =========================================================================
  // 7. ROYAL CANADIAN SEA CADETS (RCSCC)
  // =========================================================================
  {
    id: 'rcscc-328-atlantic',
    name: 'RCSCC 328 Atlantic',
    corpsNum: '328',
    type: 'sea_cadet',
    typeLabel: 'Royal Canadian Sea Cadets',
    category: 'cadet',
    lat: 49.1720,
    lng: -57.4330,
    location: 'Deer Lake',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '⚓',
    details: 'Local Deer Lake Sea Cadet Corps. Conducts comprehensive naval seamanship, small-craft sailing, ceremonial band, and biathlon training in the Humber Valley.'
  },
  {
    id: 'rcscc-194-bonaventure',
    name: 'RCSCC 194 Bonaventure',
    corpsNum: '194',
    type: 'sea_cadet',
    typeLabel: 'Royal Canadian Sea Cadets',
    category: 'cadet',
    lat: 48.9510,
    lng: -57.9480,
    location: 'Corner Brook (Blomidon Barracks)',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '⚓',
    details: 'Historic western Newfoundland Sea Cadet Corps named after HMCS Bonaventure. Active on the Bay of Islands.'
  },
  {
    id: 'rcscc-166-fort-townshend',
    name: 'RCSCC 166 Fort Townshend',
    corpsNum: '166',
    type: 'sea_cadet',
    typeLabel: 'Royal Canadian Sea Cadets',
    category: 'cadet',
    lat: 47.5620,
    lng: -52.7150,
    location: 'St. John\'s (HMCS Cabot / Fort Townshend)',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '⚓',
    details: 'Premier Newfoundland Sea Cadet Corps parading at HMCS Cabot naval reserve division overlooking St. John\'s Harbour.'
  },
  {
    id: 'rcscc-1-magnificent',
    name: 'RCSCC 1 Magnificent',
    corpsNum: '1',
    type: 'sea_cadet',
    typeLabel: 'Royal Canadian Sea Cadets',
    category: 'cadet',
    lat: 44.6650,
    lng: -63.5700,
    location: 'Dartmouth / Halifax',
    province: 'Nova Scotia',
    region: 'Atlantic',
    badge: '⚓',
    details: 'Canada\'s historic first-numbered Sea Cadet Corps, affiliated directly with the Atlantic Fleet at HMC Dockyard Halifax.'
  },
  {
    id: 'rcscc-63-falkland',
    name: 'RCSCC 63 Falkland',
    corpsNum: '63',
    type: 'sea_cadet',
    typeLabel: 'Royal Canadian Sea Cadets',
    category: 'cadet',
    lat: 45.4180,
    lng: -75.7020,
    location: 'Ottawa (HMCS Carleton, Dow\'s Lake)',
    province: 'Ontario',
    region: 'Central',
    badge: '⚓',
    details: 'National Capital Region Sea Cadet Corps based at HMCS Carleton on Dow\'s Lake.'
  },
  {
    id: 'rcscc-52-harwood',
    name: 'RCSCC 52 Harwood',
    corpsNum: '52',
    type: 'sea_cadet',
    typeLabel: 'Royal Canadian Sea Cadets',
    category: 'cadet',
    lat: 43.8500,
    lng: -79.0200,
    location: 'Ajax, Lake Ontario',
    province: 'Ontario',
    region: 'Central',
    badge: '⚓',
    details: 'Named in honour of Admiral Sir Henry Harwood, victor of the Battle of the River Plate.'
  },
  {
    id: 'rcscc-93-undaunted',
    name: 'RCSCC 93 Undaunted',
    corpsNum: '93',
    type: 'sea_cadet',
    typeLabel: 'Royal Canadian Sea Cadets',
    category: 'cadet',
    lat: 51.0450,
    lng: -114.0700,
    location: 'Calgary (HMCS Tecumseh)',
    province: 'Alberta',
    region: 'Northwest',
    badge: '⚓',
    details: 'One of Western Canada\'s largest sea cadet corps, parading at naval reserve division HMCS Tecumseh.'
  },
  {
    id: 'rcscc-2-captain-vancouver',
    name: 'RCSCC 2 Captain Vancouver',
    corpsNum: '2',
    type: 'sea_cadet',
    typeLabel: 'Royal Canadian Sea Cadets',
    category: 'cadet',
    lat: 49.2850,
    lng: -123.1150,
    location: 'Vancouver (HMCS Discovery, Stanley Park)',
    province: 'British Columbia',
    region: 'Pacific',
    badge: '⚓',
    details: 'Premier Pacific Sea Cadet Corps parading at naval division HMCS Discovery on Deadman\'s Island, Stanley Park.'
  },
  {
    id: 'rcscc-5-rainbow',
    name: 'RCSCC 5 Rainbow',
    corpsNum: '5',
    type: 'sea_cadet',
    typeLabel: 'Royal Canadian Sea Cadets',
    category: 'cadet',
    lat: 48.4300,
    lng: -123.3750,
    location: 'Victoria (HMCS Malahat)',
    province: 'British Columbia',
    region: 'Pacific',
    badge: '⚓',
    details: 'Named after HMCS Rainbow, Canada\'s very first commissioned warship, parading at HMCS Malahat in Victoria Harbour.'
  },

  // =========================================================================
  // 8. ROYAL CANADIAN ARMY CADETS (RCACC)
  // =========================================================================
  {
    id: 'rcacc-2915-deer-lake',
    name: '2915 RCACC Cap-Pelé / Deer Lake',
    corpsNum: '2915',
    type: 'army_cadet',
    typeLabel: 'Royal Canadian Army Cadets',
    category: 'cadet',
    lat: 49.1735,
    lng: -57.4305,
    location: 'Deer Lake',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '⚔️',
    details: 'Local Deer Lake Army Cadet Corps affiliated with The Royal Newfoundland Regiment. Specializes in wilderness navigation, bushcraft survival, and marksmanship.'
  },
  {
    id: 'rcacc-2515-pasadena',
    name: '2515 RCACC Pasadena',
    corpsNum: '2515',
    type: 'army_cadet',
    typeLabel: 'Royal Canadian Army Cadets',
    category: 'cadet',
    lat: 49.0170,
    lng: -57.5970,
    location: 'Pasadena, Humber Valley',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '⚔️',
    details: 'Humber Valley Army Cadet Corps operating near the Pasadena Forestry Station and Sir Richard Squires Memorial Park.'
  },
  {
    id: 'rcacc-560-corner-brook',
    name: '560 RCACC Corner Brook',
    corpsNum: '560',
    type: 'army_cadet',
    typeLabel: 'Royal Canadian Army Cadets',
    category: 'cadet',
    lat: 48.9490,
    lng: -57.9470,
    location: 'Corner Brook (Gallipoli Armoury)',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '⚔️',
    details: 'Affiliated with 2nd Battalion, The Royal Newfoundland Regiment (2 RNFLDR) at the Gallipoli Armoury in Corner Brook.'
  },
  {
    id: 'rcacc-2415-stephenville',
    name: '2415 RCACC Stephenville',
    corpsNum: '2415',
    type: 'army_cadet',
    typeLabel: 'Royal Canadian Army Cadets',
    category: 'cadet',
    lat: 48.5520,
    lng: -58.5750,
    location: 'Stephenville',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '⚔️',
    details: 'Bay St. George Army Cadet Corps training in field survival, trekking, and community service.'
  },
  {
    id: 'rcacc-166-st-johns',
    name: '166 RCACC Church Lads\' Brigade',
    corpsNum: '166',
    type: 'army_cadet',
    typeLabel: 'Royal Canadian Army Cadets',
    category: 'cadet',
    lat: 47.5640,
    lng: -52.7120,
    location: 'St. John\'s (CLB Armoury)',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '⚔️',
    details: 'Historic St. John\'s Army Cadet Corps with a direct ancestral lineage to the Royal Newfoundland Regiment of the First World War.'
  },
  {
    id: 'rcacc-2835-toronto',
    name: '2835 RCACC 48th Highlanders',
    corpsNum: '2835',
    type: 'army_cadet',
    typeLabel: 'Royal Canadian Army Cadets',
    category: 'cadet',
    lat: 43.6620,
    lng: -79.3950,
    location: 'Toronto (Moss Park Armoury)',
    province: 'Ontario',
    region: 'Central',
    badge: '⚔️',
    details: 'Affiliated with the famed 48th Highlanders of Canada, featuring a premier cadet highland pipe band and military drill team.'
  },
  {
    id: 'rcacc-2379-montreal',
    name: '2379 RCACC Royal 22e Régiment',
    corpsNum: '2379',
    type: 'army_cadet',
    typeLabel: 'Royal Canadian Army Cadets',
    category: 'cadet',
    lat: 45.5120,
    lng: -73.5650,
    location: 'Montreal (Côte-des-Neiges Armoury)',
    province: 'Quebec',
    region: 'Eastern',
    badge: '⚔️',
    details: 'Affiliated with the historic Royal 22e Régiment ("The Van Doos") based at the Citadel in Quebec City.'
  },
  {
    id: 'rcacc-2483-victoria',
    name: '2483 RCACC Princess Patricia\'s',
    corpsNum: '2483',
    type: 'army_cadet',
    typeLabel: 'Royal Canadian Army Cadets',
    category: 'cadet',
    lat: 48.4410,
    lng: -123.3680,
    location: 'Victoria (Bay Street Armoury)',
    province: 'British Columbia',
    region: 'Pacific',
    badge: '⚔️',
    details: 'Affiliated with Princess Patricia\'s Canadian Light Infantry (PPCLI) at the heritage Bay Street Armoury in Victoria.'
  },
  {
    id: 'rcacc-2554-calgary',
    name: '2554 RCACC Calgary Highlanders',
    corpsNum: '2554',
    type: 'army_cadet',
    typeLabel: 'Royal Canadian Army Cadets',
    category: 'cadet',
    lat: 51.0480,
    lng: -114.0920,
    location: 'Calgary (Mewata Armoury)',
    province: 'Alberta',
    region: 'Northwest',
    badge: '⚔️',
    details: 'Parades at the historic Mewata Armoury in downtown Calgary, affiliated with The Calgary Highlanders.'
  },

  // =========================================================================
  // 9. ROYAL CANADIAN AIR CADETS (RCACS)
  // =========================================================================
  {
    id: 'rcacs-517-deer-lake',
    name: '517 F/Lt B.C. Umbach Squadron',
    corpsNum: '517',
    type: 'air_cadet',
    typeLabel: 'Royal Canadian Air Cadets',
    category: 'cadet',
    lat: 49.1742,
    lng: -57.4325,
    location: 'Deer Lake',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '✈️',
    details: 'Home squadron of Deer Lake, named in memory of Flight Lieutenant Bernard Carl Umbach. Actively trains cadets in aviation principles, meteorology, radio communications, and drone operations.'
  },
  {
    id: 'rcacs-537-gander',
    name: '537 Gander Squadron',
    corpsNum: '537',
    type: 'air_cadet',
    typeLabel: 'Royal Canadian Air Cadets',
    category: 'cadet',
    lat: 48.9570,
    lng: -54.6150,
    location: 'Gander (9 Wing Gander)',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '✈️',
    details: 'Based at the historic crossroads of the world in Gander, training alongside RCAF 103 Search & Rescue Squadron.'
  },
  {
    id: 'rcacs-510-st-johns',
    name: '510 Lions Squadron',
    corpsNum: '510',
    type: 'air_cadet',
    typeLabel: 'Royal Canadian Air Cadets',
    category: 'cadet',
    lat: 47.5750,
    lng: -52.7300,
    location: 'St. John\'s (Torbay / Pleasantville)',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '✈️',
    details: 'One of the oldest and largest air cadet squadrons in Newfoundland, parading at the historic Torbay airport site.'
  },
  {
    id: 'rcacs-545-corner-brook',
    name: '545 Niagara Falls / Corner Brook Detachment',
    corpsNum: '545',
    type: 'air_cadet',
    typeLabel: 'Royal Canadian Air Cadets',
    category: 'cadet',
    lat: 48.9500,
    lng: -57.9420,
    location: 'Corner Brook',
    province: 'Newfoundland and Labrador',
    region: 'Atlantic',
    badge: '✈️',
    details: 'Western Newfoundland air cadet unit providing youth ground school and soaring flights.'
  },
  {
    id: 'rcacs-638-carleton',
    name: '638 District of Carleton Squadron',
    corpsNum: '638',
    type: 'air_cadet',
    typeLabel: 'Royal Canadian Air Cadets',
    category: 'cadet',
    lat: 45.3180,
    lng: -75.7800,
    location: 'Ottawa / Nepean',
    province: 'Ontario',
    region: 'Central',
    badge: '✈️',
    details: 'Leading National Capital Region squadron with an active flight simulation lab, brass-and-reed band, and aerospace team.'
  },
  {
    id: 'rcacs-2-chicago-toronto',
    name: '2 Princess Patricia Squadron',
    corpsNum: '2',
    type: 'air_cadet',
    typeLabel: 'Royal Canadian Air Cadets',
    category: 'cadet',
    lat: 43.6850,
    lng: -79.4000,
    location: 'Toronto (Fort York Armoury)',
    province: 'Ontario',
    region: 'Central',
    badge: '✈️',
    details: 'One of the original charter squadrons of the Air Cadet League of Canada (1941).'
  },
  {
    id: 'rcacs-52-calgary',
    name: '52 City of Calgary Squadron',
    corpsNum: '52',
    type: 'air_cadet',
    typeLabel: 'Royal Canadian Air Cadets',
    category: 'cadet',
    lat: 51.0800,
    lng: -114.0400,
    location: 'Calgary',
    province: 'Alberta',
    region: 'Northwest',
    badge: '✈️',
    details: 'Major Western Canada squadron parading over 200 cadets annually with extensive flight training scholarship records.'
  },
  {
    id: 'rcacs-176-winnipeg',
    name: '176 Boeing of Canada Squadron',
    corpsNum: '176',
    type: 'air_cadet',
    typeLabel: 'Royal Canadian Air Cadets',
    category: 'cadet',
    lat: 49.8800,
    lng: -97.1800,
    location: 'Winnipeg (Minto Armoury)',
    province: 'Manitoba',
    region: 'Northwest',
    badge: '✈️',
    details: 'Sponsored by aerospace giant Boeing Canada, providing specialized composite aircraft manufacturing tours and flight simulator ground school.'
  },
  {
    id: 'rcacs-655-richmond',
    name: '655 Richmond Squadron',
    corpsNum: '655',
    type: 'air_cadet',
    typeLabel: 'Royal Canadian Air Cadets',
    category: 'cadet',
    lat: 49.1650,
    lng: -123.1350,
    location: 'Richmond / Vancouver International (YVR)',
    province: 'British Columbia',
    region: 'Pacific',
    badge: '✈️',
    details: 'Largest air cadet squadron in Canada with over 350 active cadets operating immediately adjacent to Vancouver International Airport.'
  },
  {
    id: 'rcacs-89-whitehorse',
    name: '89 Wolverine Squadron',
    corpsNum: '89',
    type: 'air_cadet',
    typeLabel: 'Royal Canadian Air Cadets',
    category: 'cadet',
    lat: 60.7200,
    lng: -135.0700,
    location: 'Whitehorse',
    province: 'Yukon',
    region: 'North',
    badge: '✈️',
    details: 'Northern territorial air cadet squadron flying in mountainous Sub-Arctic airspace.'
  },
  {
    id: 'rcacs-825-yellowknife',
    name: '825 Elks Yellowknife Squadron',
    corpsNum: '825',
    type: 'air_cadet',
    typeLabel: 'Royal Canadian Air Cadets',
    category: 'cadet',
    lat: 62.4500,
    lng: -114.3800,
    location: 'Yellowknife',
    province: 'Northwest Territories',
    region: 'North',
    badge: '✈️',
    details: 'Northwest Territories squadron training northern youth in arctic aviation, bush navigation, and survival alongside 440 Transport Sqn.'
  }
];
