import 'leaflet/dist/leaflet.css'
import './style.css'
import L from 'leaflet'

// Map Themes
const MAP_THEMES = {
  dark: 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',
  light: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',
  sea: 'https://server.arcgisonline.com/ArcGIS/rest/services/Ocean/World_Ocean_Base/MapServer/tile/{z}/{y}/{x}',
  satellite: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
  street: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
  'night-vision': 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png'
};

const defaultCenter = [49.0342, -57.5955]; 
const defaultZoom = 13;

// --- Initialize Maps ---
const primaryMap = L.map('primary-map', {
  zoomControl: true,
  minZoom: 5,
  maxZoom: 18,
  zoomAnimation: false // Snappier for tactical feel
}).setView(defaultCenter, defaultZoom);

// --- Dynamic Scale Control ---
let currentScaleMode = 0; // 0 = Both, 1 = Metric, 2 = Imperial
let isScaleVisible = true;
const scaleOptions = [
  { metric: true, imperial: true, position: 'bottomleft', maxWidth: 250 },
  { metric: true, imperial: false, position: 'bottomleft', maxWidth: 250 },
  { metric: false, imperial: true, position: 'bottomleft', maxWidth: 250 }
];

let scaleControl = L.control.scale(scaleOptions[currentScaleMode]).addTo(primaryMap);

function bindScaleClick() {
  const container = scaleControl.getContainer();
  if (!container) return;
  container.style.cursor = 'pointer';
  container.title = 'Click to toggle scale units (Metric/Imperial)';
  
  // Custom HUD styling for the scale - make it larger and chunkier
  container.style.background = 'rgba(0, 0, 0, 0.7)';
  container.style.border = '2px solid var(--border-color)';
  container.style.backdropFilter = 'blur(6px)';
  container.style.padding = '6px 12px';
  container.style.color = 'var(--accent-color)';
  container.style.fontFamily = 'var(--hud-font)';
  container.style.fontSize = '14px';
  container.style.fontWeight = 'bold';
  container.style.boxShadow = '0 0 10px rgba(0,0,0,0.8), inset 0 0 10px rgba(47, 129, 247, 0.2)';
  
  // Style inner lines generated by leaflet
  const lines = container.querySelectorAll('.leaflet-control-scale-line');
  lines.forEach(line => {
    line.style.color = 'var(--accent-color)';
    line.style.border = '2px solid var(--accent-color)';
    line.style.borderTop = 'none';
    line.style.background = 'transparent';
    line.style.textShadow = '0 0 5px var(--accent-glow)';
    line.style.paddingBottom = '4px';
    line.style.paddingTop = '4px';
    line.style.fontSize = '14px';
  });

  container.onclick = (e) => {
    e.stopPropagation();
    primaryMap.removeControl(scaleControl);
    currentScaleMode = (currentScaleMode + 1) % 3;
    scaleControl = L.control.scale(scaleOptions[currentScaleMode]).addTo(primaryMap);
    bindScaleClick();
  };
}
bindScaleClick();

// Visibility Toggle Logic
const scaleToggleBtn = document.getElementById('scale-toggle');
if (scaleToggleBtn) {
  scaleToggleBtn.addEventListener('change', (e) => {
    isScaleVisible = e.target.checked;
    if (isScaleVisible) {
      scaleControl.addTo(primaryMap);
      bindScaleClick();
      logToFeed("SYS: MAP SCALE ONLINE");
    } else {
      primaryMap.removeControl(scaleControl);
      logToFeed("SYS: MAP SCALE OFFLINE");
    }
  });
}

const minimapOptions = {
  zoomControl: false, attributionControl: false, dragging: false, 
  touchZoom: false, scrollWheelZoom: false, doubleClickZoom: false, boxZoom: false,
  zoomAnimation: false
};

// Buoys Map is independent and focused on the lake
const secondaryMap1 = L.map('secondary-map-1', {
  zoomControl: true,
  zoomAnimation: false
}).setView([49.0342, -57.5955], 14); // Centered on Buoys

// EMS Map is independent and focused on the Hospital
const secondaryMap2 = L.map('secondary-map-2', {
  zoomControl: true,
  zoomAnimation: false
}).setView([48.92898, -57.92175], 15); // Centered on Hospital

// Radar Map is independent and interactive
const secondaryMap3 = L.map('secondary-map-3', {
  zoomControl: true,
  zoomAnimation: false
}).setView([48.5, -56.0], 6); // Centered on Newfoundland

// Forestry Map is independent and focused on Pasadena Forestry Center
const secondaryMap4 = L.map('secondary-map-4', {
  zoomControl: true,
  zoomAnimation: false
}).setView([49.0149167, -57.5865278], 15); // Centered on Pasadena Forestry Center

// Feature: Click any minimap to sync the primary map to its exact view
[secondaryMap1, secondaryMap2, secondaryMap3, secondaryMap4].forEach(miniMap => {
  miniMap.on('click', () => {
    primaryMap.flyTo(miniMap.getCenter(), miniMap.getZoom(), {
      duration: 0.6,
      easeLinearity: 0.25
    });
  });
});

let currentTiles = [];

function setMapTiles(themeKey) {
  const url = MAP_THEMES[themeKey] || MAP_THEMES.dark;
  
  let maxNative = 20;
  if (themeKey === 'sea') maxNative = 13;
  if (themeKey === 'satellite') maxNative = 18;
  if (themeKey === 'street') maxNative = 19;
  
  currentTiles.forEach(t => t.remove());
  currentTiles = [];
  currentTiles.push(L.tileLayer(url, { maxZoom: 20, maxNativeZoom: maxNative }).addTo(primaryMap));
  currentTiles.push(L.tileLayer(url, { maxZoom: 20, maxNativeZoom: maxNative }).addTo(secondaryMap1));
  currentTiles.push(L.tileLayer(url, { maxZoom: 20, maxNativeZoom: maxNative }).addTo(secondaryMap2));
  currentTiles.push(L.tileLayer(url, { maxZoom: 20, maxNativeZoom: maxNative }).addTo(secondaryMap3));
  currentTiles.push(L.tileLayer(url, { maxZoom: 20, maxNativeZoom: maxNative }).addTo(secondaryMap4));
}

// --- Theme Switcher Logic ---
const themeSelect = document.getElementById('theme-select');

function applyTheme(theme) {
  let activeTheme = theme;
  if (theme === 'system') {
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    activeTheme = prefersDark ? 'dark' : 'light';
  }
  document.documentElement.setAttribute('data-theme', activeTheme);
  setMapTiles(activeTheme);
}

themeSelect.addEventListener('change', (e) => {
  const newTheme = e.target.value;
  localStorage.setItem('cmd-theme', newTheme);
  applyTheme(newTheme);
});

const savedTheme = localStorage.getItem('cmd-theme') || 'dark';
themeSelect.value = savedTheme;
applyTheme(savedTheme);


// --- Functional Intel Feed ---
const feedEl = document.getElementById('activity-feed');

function logToFeed(msg, isAlert = false) {
  const now = new Date();
  const timeStr = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}:${String(now.getSeconds()).padStart(2, '0')}`;
  
  const li = document.createElement('li');
  if (isAlert) li.className = 'alert';
  
  const prefix = `<span class="timestamp">[${timeStr}]</span> ${isAlert ? 'WARNING: ' : '> '}`;
  li.innerHTML = prefix + msg;
  
  feedEl.appendChild(li);
  
  if (feedEl.children.length > 8) {
    feedEl.removeChild(feedEl.firstChild);
  }
}

setTimeout(() => logToFeed("CMD CTR SYSTEM INITIALIZED"), 1500);


// --- Weather Radar Logic (RainViewer) ---
const radarToggle = document.getElementById('radar-toggle');
let radarLayer = null;

async function toggleRadar() {
  if (radarToggle.checked) {
    logToFeed("SYS: WEATHER RADAR ONLINE");
    try {
      const res = await fetch('https://api.rainviewer.com/public/weather-maps.json');
      const data = await res.json();
      const latestPath = data.radar.past[data.radar.past.length - 1].path;
      const radarUrl = `${data.host}${latestPath}/256/{z}/{x}/{y}/2/1_1.png`;
      
      radarLayer = L.tileLayer(radarUrl, { 
        opacity: 0.6, 
        zIndex: 1000,
        maxNativeZoom: 12
      });
      radarLayer.addTo(primaryMap);
    } catch (e) {
      logToFeed("RADAR UPLINK FAILED", true);
      radarToggle.checked = false;
    }
  } else {
    logToFeed("SYS: WEATHER RADAR OFFLINE");
    if (radarLayer) {
      radarLayer.remove();
      radarLayer = null;
    }
  }
}

radarToggle.addEventListener('change', toggleRadar);

// --- Reticle Toggle Logic ---
const reticleToggle = document.getElementById('reticle-toggle');
const crosshairEl = document.querySelector('.crosshair');

reticleToggle.addEventListener('change', (e) => {
  if (e.target.checked) {
    crosshairEl.style.display = 'block';
    logToFeed("SYS: TARGETING RETICLE ONLINE");
  } else {
    crosshairEl.style.display = 'none';
    logToFeed("SYS: TARGETING RETICLE OFFLINE");
  }
});

// Load Radar on Minimap 3 permanently
async function loadRadarMinimap() {
  try {
    const res = await fetch('https://api.rainviewer.com/public/weather-maps.json');
    const data = await res.json();
    const latestPath = data.radar.past[data.radar.past.length - 1].path;
    const radarUrl = `${data.host}${latestPath}/256/{z}/{x}/{y}/2/1_1.png`;
    
    L.tileLayer(radarUrl, { 
      opacity: 0.8, 
      zIndex: 1000,
      maxNativeZoom: 12 
    }).addTo(secondaryMap3);
  } catch (e) {
    console.error("Minimap Radar Error:", e);
  }
}
loadRadarMinimap();


// --- Open-Meteo Environmental & Marine HUD ---
const weatherReadout = document.getElementById('weather-readout');
let weatherDebounceTimer;

async function fetchWeatherAndMarine(lat, lng) {
  weatherReadout.innerHTML = `SCANNING ATMOSPHERE...`;
  try {
    // 1. Fetch Atmosphere
    const weatherRes = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lng}&current=temperature_2m,wind_speed_10m,wind_direction_10m,surface_pressure`);
    const weatherData = await weatherRes.json();
    
    // 2. Fetch Marine (Sea State)
    const marineRes = await fetch(`https://marine-api.open-meteo.com/v1/marine?latitude=${lat}&longitude=${lng}&current=wave_height,wave_direction`);
    const marineData = await marineRes.json();
    
    if (weatherData && weatherData.current) {
      const t = weatherData.current.temperature_2m;
      const ws = weatherData.current.wind_speed_10m;
      const wd = weatherData.current.wind_direction_10m;
      const sp = weatherData.current.surface_pressure;
      
      let marineHtml = `WAVES: <span class="val">INLAND/NO DATA</span>`;
      let waveLog = ``;
      
      if (marineData && marineData.current && marineData.current.wave_height !== null) {
        const wh = marineData.current.wave_height;
        const wDir = marineData.current.wave_direction;
        marineHtml = `WAVES: <span class="val">${wh}m @ ${wDir}°</span>`;
        waveLog = ` | SEA: ${wh}m @ ${wDir}°`;
      }
      
      weatherReadout.innerHTML = `
        TEMP: <span class="val">${t}°C</span><br>
        WIND: <span class="val">${ws} km/h @ ${wd}°</span><br>
        PRES: <span class="val">${sp} hPa</span><br>
        ${marineHtml}
      `;

      logToFeed(`TELEMETRY RECV: WIND ${ws}km/h @ ${wd}°${waveLog}`);
    }
  } catch (e) {
    weatherReadout.innerHTML = `<span style="color:var(--danger-color)">SENSOR INTERFERENCE DETECTED</span>`;
    logToFeed("ENV SENSOR INTERFERENCE", true);
  }
}

function handleWeatherUpdate() {
  clearTimeout(weatherDebounceTimer);
  weatherDebounceTimer = setTimeout(() => {
    const center = primaryMap.getCenter();
    const lat = center.lat.toFixed(4);
    const lng = center.lng.toFixed(4);
    logToFeed(`RE-TARGETING SENSORS TO [${lat}, ${lng}]`);
    fetchWeatherAndMarine(lat, lng);
  }, 1000); // Wait 1 second after panning stops to fetch
}


// --- Synchronization & Coordinates ---
const coordReadout = document.getElementById('coord-readout');

function updateCoordinates() {
  const center = primaryMap.getCenter();
  const lat = center.lat.toFixed(4);
  const lng = center.lng.toFixed(4);
  coordReadout.innerHTML = `LAT: ${lat}<br>LON: ${lng}`;
}

primaryMap.on('move', updateCoordinates);
primaryMap.on('moveend', handleWeatherUpdate); // Trigger weather fetch on pan end
primaryMap.on('zoom', updateCoordinates);
updateCoordinates();
handleWeatherUpdate(); // Initial fetch

// --- Expandable/Collapsible Minimap & Sidebar Logic ---
window.toggleSidebar = function() {
  const sidebar = document.getElementById('right-sidebar');
  const btn = document.getElementById('sidebar-toggle-btn');
  const isCollapsed = sidebar.classList.contains('collapsed');
  
  if (isCollapsed) {
    sidebar.classList.remove('collapsed');
    btn.classList.remove('collapsed');
    btn.textContent = '[ < MENU ]';
    logToFeed("SYS: SIDEBAR RESTORED");
  } else {
    sidebar.classList.add('collapsed');
    btn.classList.add('collapsed');
    btn.textContent = '[ MENU > ]';
    logToFeed("SYS: SIDEBAR COLLAPSED");
  }
  
  // Wait for sidebar animation to finish then tell primary map to resize
  setTimeout(() => {
    primaryMap.invalidateSize();
  }, 350);
};

window.toggleRollup = function(panelId) {
  const panel = document.getElementById(panelId);
  const btn = panel.querySelector('.expand-btn'); // Get the first one (rollup btn)
  const isRolledUp = panel.classList.contains('rolled-up');
  
  if (isRolledUp) {
    panel.classList.remove('rolled-up');
    btn.textContent = '[-]';
  } else {
    panel.classList.add('rolled-up');
    btn.textContent = '[+]';
  }
};

window.toggleExpand = function(panelId, mapVarName) {
  const panel = document.getElementById(panelId);
  const btns = panel.querySelectorAll('.expand-btn');
  const btn = btns[1]; // Get the second one (expand btn)
  const isExpanded = panel.classList.contains('expanded');
  
  if (isExpanded) {
    panel.classList.remove('expanded');
    btn.textContent = '[+]';
    logToFeed(`MINIMIZING ${panelId}`);
  } else {
    panel.classList.add('expanded');
    btn.textContent = '[-]';
    logToFeed(`EXPANDING ${panelId} TO MAIN VIEW`);
  }
  
  // We must tell Leaflet the container size changed so it redraws tiles
  setTimeout(() => {
    if (mapVarName === 'secondaryMap1') secondaryMap1.invalidateSize();
    if (mapVarName === 'secondaryMap2') secondaryMap2.invalidateSize();
    if (mapVarName === 'secondaryMap3') secondaryMap3.invalidateSize();
    if (mapVarName === 'secondaryMap4') secondaryMap4.invalidateSize();
  }, 300); // match CSS transition duration
};


// --- Clock Logic ---
const zuluEl = document.getElementById('time-zulu');
const localEl = document.getElementById('time-local');

function updateClock() {
  const now = new Date();
  
  // Zulu time
  const zh = String(now.getUTCHours()).padStart(2, '0');
  const zm = String(now.getUTCMinutes()).padStart(2, '0');
  const zs = String(now.getUTCSeconds()).padStart(2, '0');
  zuluEl.textContent = `${zh}:${zm}:${zs}Z`;

  // Local time
  const lh = String(now.getHours()).padStart(2, '0');
  const lm = String(now.getMinutes()).padStart(2, '0');
  const ls = String(now.getSeconds()).padStart(2, '0');
  localEl.textContent = `${lh}:${lm}:${ls} LOC`;
  if (now.getUTCHours() === 0 && now.getUTCMinutes() === 0) {
    dayCounter++;
  }
}
setInterval(updateClock, 1000);
updateClock();

// --- HUD Draggable & Resizable Logic ---
const hudPanels = document.querySelectorAll('.hud-panel');
hudPanels.forEach(panel => {
  const label = panel.querySelector('.hud-label');
  const panelId = panel.classList[1]; // e.g. clock-panel
  if (!label || !panelId) return;

  const contentContainer = panel.querySelector('div:not(.hud-label), ul');
  let baseWidth = panel.offsetWidth;

  // Restore saved state
  const HUD_VERSION = "v2";
  const savedState = localStorage.getItem('hud_state_' + HUD_VERSION + '_' + panelId);
  if (savedState) {
    const state = JSON.parse(savedState);
    if (state.top && state.left) {
      panel.style.top = state.top;
      panel.style.left = state.left;
      panel.style.bottom = 'auto';
      panel.style.right = 'auto';
    }
    if (state.width) panel.style.width = state.width;
    if (state.height) panel.style.height = state.height;
    if (state.zoom && contentContainer) contentContainer.style.zoom = state.zoom;
    baseWidth = state.baseWidth || panel.offsetWidth;
  }

  // Save state when resized (using ResizeObserver)
  const resizeObserver = new ResizeObserver((entries) => {
    for (let entry of entries) {
      if (!baseWidth) baseWidth = panel.offsetWidth;
      
      const newWidth = entry.borderBoxSize ? entry.borderBoxSize[0].inlineSize : panel.offsetWidth;
      if (newWidth && baseWidth && contentContainer) {
        const scale = newWidth / baseWidth;
        // Don't apply zoom if it's the first render or a tiny glitch
        if (scale > 0.1 && Math.abs(scale - 1.0) > 0.05) {
          contentContainer.style.zoom = scale;
        }
      }
    }
    savePanelState(panel, panelId, contentContainer ? contentContainer.style.zoom : null, baseWidth);
  });
  resizeObserver.observe(panel);

  // Drag logic
  let isDragging = false;
  let startX, startY, initialLeft, initialTop;

  label.addEventListener('mousedown', (e) => {
    isDragging = true;
    startX = e.clientX;
    startY = e.clientY;

    // Use offset to avoid jumping relative to parent
    initialLeft = panel.offsetLeft;
    initialTop = panel.offsetTop;

    panel.style.right = 'auto';
    panel.style.bottom = 'auto';
    panel.style.left = initialLeft + 'px';
    panel.style.top = initialTop + 'px';

    hudPanels.forEach(p => p.style.zIndex = 1000);
    panel.style.zIndex = 1001;
  });

  document.addEventListener('mousemove', (e) => {
    if (!isDragging) return;
    const dx = e.clientX - startX;
    const dy = e.clientY - startY;
    panel.style.left = (initialLeft + dx) + 'px';
    panel.style.top = (initialTop + dy) + 'px';
  });

  document.addEventListener('mouseup', () => {
    if (isDragging) {
      isDragging = false;
      savePanelState(panel, panelId, contentContainer ? contentContainer.style.zoom : null, baseWidth);
    }
  });
});

function savePanelState(panel, panelId, zoomScale, baseWidth) {
  const state = {
    top: panel.style.top,
    left: panel.style.left,
    width: panel.style.width,
    height: panel.style.height,
    zoom: zoomScale,
    baseWidth: baseWidth
  };
  localStorage.setItem('hud_state_v2_' + panelId, JSON.stringify(state));
}

// --- Load Data Layers with Radar Blips ---
function getCustomIcon(feature) {
  const type = feature.properties.markerType || 'blip';
  const color = feature.properties.markerColor || 'red';
  
  if (type === 'blip') {
    return L.divIcon({
      className: `radar-blip blip-${color}`,
      iconSize: [20, 20],
      iconAnchor: [10, 10]
    });
  } else {
    // Marine SVGs
    let svgPath = '';
    if (type === 'anchor') {
      svgPath = '<circle cx="12" cy="5" r="3"></circle><line x1="12" y1="22" x2="12" y2="8"></line><path d="M5 12H2a10 10 0 0 0 20 0h-3"></path>';
    } else if (type === 'warning') {
      svgPath = '<path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path><line x1="12" y1="9" x2="12" y2="13"></line><line x1="12" y1="17" x2="12.01" y2="17"></line>';
    } else if (type === 'buoy') {
      svgPath = '<path d="M12 2v20"></path><path d="M8 6h8"></path><path d="M6 14h12"></path><path d="M4 22h16"></path><path d="M6 10l6-4 6 4"></path>';
    } else if (type === 'target') {
      svgPath = '<circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle>';
    } else if (type === 'building') {
      svgPath = '<rect x="4" y="2" width="16" height="20" rx="2" ry="2"></rect><path d="M9 22v-4h6v4"></path><path d="M8 6h.01"></path><path d="M16 6h.01"></path><path d="M12 6h.01"></path><path d="M12 10h.01"></path><path d="M12 14h.01"></path><path d="M16 10h.01"></path><path d="M16 14h.01"></path><path d="M8 10h.01"></path><path d="M8 14h.01"></path>';
    } else if (type === 'utensils') {
      svgPath = '<path d="M3 2v7c0 1.1.9 2 2 2h4a2 2 0 0 0 2-2V2"></path><path d="M7 2v20"></path><path d="M21 15V2v0a5 5 0 0 0-5 5v6c0 1.1.9 2 2 2h3Zm0 0v7"></path>';
    } else if (type === 'bath') {
      svgPath = '<path d="M9 6 6.5 3.5a1.5 1.5 0 0 0-1-.5C4.683 3 4 3.683 4 4.5V17a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-5"></path><path d="M10 5 L10 5.01"></path><path d="M12 7 L12 7.01"></path><path d="M14 4 L14 4.01"></path>';
    } else if (type === 'warehouse') {
      svgPath = '<path d="M22 8.35V20a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V8.35A2 2 0 0 1 3.26 6.5l8-3.2a2 2 0 0 1 1.48 0l8 3.2A2 2 0 0 1 22 8.35Z"></path><path d="M6 18h12"></path><path d="M6 14h12"></path><rect width="12" height="12" x="6" y="10"></rect>';
    }
    
    return L.divIcon({
      className: `marine-icon`, // No background, just wrapper
      html: `<div class="marine-icon-wrapper"><svg viewBox="0 0 24 24" width="24" height="24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" class="svg-${color}">${svgPath}</svg></div>`,
      iconSize: [24, 24],
      iconAnchor: [12, 12]
    });
  }
}

const emergencyIcon = L.divIcon({
  className: 'radar-blip blip-cyan',
  iconSize: [20, 20],
  iconAnchor: [10, 10]
});

// --- Edit Mode Logic ---
let isEditMode = false;
const editToggle = document.getElementById('edit-toggle');

editToggle.addEventListener('change', (e) => {
  isEditMode = e.target.checked;
  if (isEditMode) {
    document.getElementById('primary-map-container').style.cursor = 'crosshair';
    logToFeed("SYS: TACTICAL EDIT MODE ONLINE", true);
  } else {
    document.getElementById('primary-map-container').style.cursor = '';
    logToFeed("SYS: TACTICAL EDIT MODE OFFLINE");
  }
});

// Modal Logic
let pendingDeployCoords = null;
const modal = document.getElementById('deployment-modal');
const deployNameInput = document.getElementById('deploy-name');

document.querySelectorAll('.cat-btn').forEach(btn => {
  btn.addEventListener('click', (e) => {
    document.querySelectorAll('.cat-btn').forEach(b => b.classList.remove('active'));
    e.target.classList.add('active');
    
    document.getElementById('marker-grid-radar').style.display = 'none';
    document.getElementById('marker-grid-marine').style.display = 'none';
    document.getElementById('marker-grid-infrastructure').style.display = 'none';
    
    const targetGrid = document.getElementById(`marker-grid-${e.target.dataset.cat}`);
    targetGrid.style.display = 'grid';
    
    // Auto-select first option in the active grid
    document.querySelectorAll('.marker-option').forEach(o => o.classList.remove('selected'));
    targetGrid.querySelector('.marker-option').classList.add('selected');
  });
});

document.querySelectorAll('.marker-option').forEach(opt => {
  opt.addEventListener('click', (e) => {
    document.querySelectorAll('.marker-option').forEach(o => o.classList.remove('selected'));
    e.currentTarget.classList.add('selected');
  });
});

document.getElementById('btn-abort').addEventListener('click', () => {
  modal.style.display = 'none';
  pendingDeployCoords = null;
});

document.getElementById('btn-deploy').addEventListener('click', () => {
  const name = deployNameInput.value.trim() || "ALPHA-" + Math.floor(Math.random() * 100);
  const selectedOpt = document.querySelector('.marker-option.selected');
  const type = selectedOpt ? selectedOpt.dataset.type : 'blip';
  const color = selectedOpt ? selectedOpt.dataset.color : 'red';
  
  const newId = "CUSTOM-" + Date.now();
  logToFeed(`> DEPLOYING: ${name}...`);
  
  let customBuoys = JSON.parse(localStorage.getItem('custom_buoys') || '[]');
  customBuoys.push({ id: newId, name: name, lat: pendingDeployCoords.lat, lng: pendingDeployCoords.lng, markerType: type, markerColor: color });
  localStorage.setItem('custom_buoys', JSON.stringify(customBuoys));
  
  logToFeed(`> DEPLOYED NEW BUOY: ${name}`);
  modal.style.display = 'none';
  pendingDeployCoords = null;
  renderBuoys();
});

primaryMap.on('click', async (e) => {
  if (!isEditMode) return;
  pendingDeployCoords = e.latlng;
  deployNameInput.value = "";
  modal.style.display = 'flex';
  deployNameInput.focus();
});

// --- GPS Tracking Logic ---
let watchId = null;
let gpsMarker = null;

const gpsIcon = L.divIcon({
  className: 'gps-blip',
  iconSize: [24, 24],
  iconAnchor: [12, 12]
});

document.getElementById('gps-track-toggle').addEventListener('change', (e) => {
  if (e.target.checked) {
    if ("geolocation" in navigator) {
      logToFeed("SYS: GPS TRACKING ACTIVATED", true);
      watchId = navigator.geolocation.watchPosition(
        (position) => {
          const latlng = [position.coords.latitude, position.coords.longitude];
          if (!gpsMarker) {
            gpsMarker = L.marker(latlng, { icon: gpsIcon, zIndexOffset: 1000 }).addTo(primaryMap);
            gpsMarker.bindPopup("<strong>YOUR DEVICE</strong>");
          } else {
            gpsMarker.setLatLng(latlng);
          }
        },
        (error) => {
          logToFeed(`SYS ERROR: GPS SIGNAL LOST (${error.message})`, true);
          e.target.checked = false;
        },
        { enableHighAccuracy: true, maximumAge: 0 }
      );
    } else {
      logToFeed("SYS ERROR: GPS NOT SUPPORTED", true);
      e.target.checked = false;
    }
  } else {
    logToFeed("SYS: GPS TRACKING DEACTIVATED");
    if (watchId !== null) navigator.geolocation.clearWatch(watchId);
    if (gpsMarker) {
      primaryMap.removeLayer(gpsMarker);
      gpsMarker = null;
    }
  }
});

document.getElementById('btn-gps-deploy').addEventListener('click', () => {
  if ("geolocation" in navigator) {
    logToFeed("> ACQUIRING GPS LOCK...");
    navigator.geolocation.getCurrentPosition(
      (position) => {
        logToFeed("> GPS LOCK ACQUIRED");
        pendingDeployCoords = { lat: position.coords.latitude, lng: position.coords.longitude };
        deployNameInput.value = "";
        modal.style.display = 'flex';
        deployNameInput.focus();
      },
      (error) => {
        logToFeed(`SYS ERROR: GPS LOCK FAILED (${error.message})`, true);
      },
      { enableHighAccuracy: true, timeout: 10000 }
    );
  } else {
    logToFeed("SYS ERROR: GPS NOT SUPPORTED", true);
  }
});

// --- Buoy Rendering Logic ---
const buoysLayerPrimary = L.layerGroup().addTo(primaryMap);
const buoysLayerSecondary = L.layerGroup().addTo(secondaryMap1);

async function renderBuoys() {
  logToFeed('[TRACE] renderBuoys started');
  buoysLayerPrimary.clearLayers();
  buoysLayerSecondary.clearLayers();
  
  let allFeatures = [];
  if (typeof window.json_Buoys_2 !== 'undefined' && window.json_Buoys_2.features) {
    allFeatures = [...window.json_Buoys_2.features];
    logToFeed(`[TRACE] Added ${allFeatures.length} Base Buoys`);
  } else {
    logToFeed('[TRACE] Base Buoys UNDEFINED');
  }
  
  try {
    logToFeed('[TRACE] Fetching custom buoys...');
    const supaBuoys = JSON.parse(localStorage.getItem('custom_buoys') || '[]');
    const error = null;
      
    if (error) {
      logToFeed(`[TRACE] Supabase err: ${error.message}`);
    } else if (supaBuoys) {
      logToFeed(`[TRACE] Added ${supaBuoys.length} Custom Buoys`);
      supaBuoys.forEach(b => {
        allFeatures.push({
          type: "Feature",
          properties: { id: b.id, Buoys: b.name, isCustom: true, markerType: b.markerType, markerColor: b.markerColor },
          geometry: { type: "Point", coordinates: [b.lng, b.lat] }
        });
      });
    }
  } catch (err) {
    logToFeed(`[TRACE] Supabase throw: ${err.message}`);
  }
  
  logToFeed(`[TRACE] Filtering deleted base buoys...`);
  let deletedBase = [];
  try {
    deletedBase = JSON.parse(localStorage.getItem('deleted_base_buoys') || '[]');
  } catch(e) {
    logToFeed(`[TRACE] localStorage err: ${e.message}`);
  }
  
  const visibleFeatures = allFeatures.filter(f => !deletedBase.includes(f.properties.id));
  logToFeed(`[TRACE] Rendering ${visibleFeatures.length} visible buoys...`);

  const onFeatureClick = (feature, layer) => {
    // Add click interceptor for Edit Mode
    layer.on('click', async (e) => {
      if (isEditMode) {
        logToFeed(`[TRACE] Click intercepted for buoy: ${feature.properties['Buoys']}`);
        if (confirm(`Remove Tactical Buoy: ${feature.properties['Buoys']}?`)) {
          if (feature.properties.isCustom) {
            logToFeed(`[TRACE] Removing custom buoy: ${feature.properties.id}`);
            // Remove from local storage
            let customBuoys = JSON.parse(localStorage.getItem('custom_buoys') || '[]');
            customBuoys = customBuoys.filter(b => b.id !== feature.properties.id);
            localStorage.setItem('custom_buoys', JSON.stringify(customBuoys));
            const error = null;
            if (!error) {
              logToFeed(`> REMOVED BUOY: ${feature.properties['Buoys']}`, true);
            } else {
              logToFeed(`[TRACE] Supabase delete err: ${error.message}`);
              logToFeed(`SYS ERROR: FAILED TO REMOVE BUOY`);
            }
          } else {
             // For base buoys, add to hidden list in local storage
             logToFeed(`[TRACE] Removing base buoy: ${feature.properties.id}`);
             let deletedBase = JSON.parse(localStorage.getItem('deleted_base_buoys') || '[]');
             deletedBase.push(feature.properties.id);
             localStorage.setItem('deleted_base_buoys', JSON.stringify(deletedBase));
             logToFeed(`> REMOVED BUOY: ${feature.properties['Buoys']}`, true);
          }
          renderBuoys();
        }
      }
    });
    
    // Setup normal popup
    const id = feature.properties['id'] || 'N/A';
    const name = feature.properties['Buoys'] || 'Unnamed Buoy';
    layer.bindPopup(`<strong>TACTICAL BUOY</strong><br/>ID: ${id}<br/>NAME: ${name}`);
  };

  try {
    L.geoJSON({ type: "FeatureCollection", features: visibleFeatures }, {
      pointToLayer: (feature, latlng) => L.marker(latlng, { icon: getCustomIcon(feature) }),
      onEachFeature: onFeatureClick
    }).addTo(buoysLayerPrimary);

    const geojsonSecondary = L.geoJSON({ type: "FeatureCollection", features: visibleFeatures }, {
      pointToLayer: (feature, latlng) => L.marker(latlng, { icon: getCustomIcon(feature) })
    }).addTo(buoysLayerSecondary);

    if (visibleFeatures.length > 0) {
      setTimeout(() => {
        secondaryMap1.fitBounds(geojsonSecondary.getBounds(), { padding: [10, 10], maxZoom: 16 });
      }, 100);
    }
    logToFeed('[TRACE] L.geoJSON success');
  } catch(e) {
    logToFeed(`[TRACE] L.geoJSON ERROR: ${e.message}`, true);
  }
}

// Initial render handled by waitForDataAndRender()

// --- Supabase Realtime Subscription ---
// --- Local Custom Buoys logic replaces Supabase Realtime ---
// No realtime channel needed for local storage

// Emergency Services
function emergencyPopup(feature, layer) {
  const id = feature.properties['id'] || 'N/A';
  const name = feature.properties['EMS Loc'] || 'Emergency Service';
  layer.bindPopup(`<strong>EMERGENCY UNIT</strong><br/>ID: ${id}<br/>LOC: ${name}`);
}

function renderEmergencyServices() {
  if (typeof window.json_emergency_3 !== 'undefined') {
    try {
      const layer1 = L.geoJSON(window.json_emergency_3, {
        pointToLayer: (feature, latlng) => L.marker(latlng, { icon: emergencyIcon }),
        onEachFeature: emergencyPopup
      }).addTo(primaryMap);

      const layer2 = L.geoJSON(window.json_emergency_3, {
        pointToLayer: (feature, latlng) => L.marker(latlng, { icon: emergencyIcon })
      }).addTo(secondaryMap2);
      
      const count = layer1.getLayers().length;
      logToFeed(`[DIAG] EMS RENDERED: ${count} markers.`);
    } catch(err) {
      logToFeed(`[DIAG] EMS ERROR: ${err.message}`, true);
    }
  } else {
    logToFeed(`[DIAG] EMS DATA MISSING`);
  }
}

// Data Initialization Poller
let retryCount = 0;
function waitForDataAndRender() {
  if (typeof window.json_Buoys_2 !== 'undefined' && typeof window.json_emergency_3 !== 'undefined') {
    logToFeed(`[DIAG] QGIS Data Loaded in ${retryCount * 100}ms`);
    renderBuoys().then(() => {
      const bCount = buoysLayerPrimary.getLayers().length;
      logToFeed(`[DIAG] BUOYS RENDERED: ${bCount} markers.`);
    }).catch(e => logToFeed(`[DIAG] BUOY ERR: ${e.message}`));
    renderEmergencyServices();
  } else if (retryCount < 20) {
    retryCount++;
    setTimeout(waitForDataAndRender, 100);
  } else {
    logToFeed("SYS ERROR: QGIS DATA FILES MISSING", true);
    renderBuoys();
  }
}

// Start data polling
waitForDataAndRender();

setTimeout(() => {
  primaryMap.invalidateSize();
  secondaryMap1.invalidateSize();
  secondaryMap2.invalidateSize();
  secondaryMap3.invalidateSize();
  secondaryMap4.invalidateSize();
}, 500);
